
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `OfficialTranslationWord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OfficialTranslationWord
 *
 */
export type OfficialTranslationWordModel = runtime.Types.Result.DefaultSelection<Prisma.$OfficialTranslationWordPayload>

export type AggregateOfficialTranslationWord = {
  _count: OfficialTranslationWordCountAggregateOutputType | null
  _min: OfficialTranslationWordMinAggregateOutputType | null
  _max: OfficialTranslationWordMaxAggregateOutputType | null
}

export type OfficialTranslationWordMinAggregateOutputType = {
  id: string | null
  text: string | null
  language: string | null
  note: string | null
  wordId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OfficialTranslationWordMaxAggregateOutputType = {
  id: string | null
  text: string | null
  language: string | null
  note: string | null
  wordId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OfficialTranslationWordCountAggregateOutputType = {
  id: number
  text: number
  language: number
  note: number
  wordId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OfficialTranslationWordMinAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  wordId?: true
  createdAt?: true
  updatedAt?: true
}

export type OfficialTranslationWordMaxAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  wordId?: true
  createdAt?: true
  updatedAt?: true
}

export type OfficialTranslationWordCountAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  wordId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OfficialTranslationWordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfficialTranslationWord to aggregate.
   */
  where?: Prisma.OfficialTranslationWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialTranslationWords to fetch.
   */
  orderBy?: Prisma.OfficialTranslationWordOrderByWithRelationInput | Prisma.OfficialTranslationWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.OfficialTranslationWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialTranslationWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialTranslationWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned OfficialTranslationWords
  **/
  _count?: true | OfficialTranslationWordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
  **/
  _min?: OfficialTranslationWordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
  **/
  _max?: OfficialTranslationWordMaxAggregateInputType
}

export type GetOfficialTranslationWordAggregateType<T extends OfficialTranslationWordAggregateArgs> = {
      [P in keyof T & keyof AggregateOfficialTranslationWord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOfficialTranslationWord[P]>
    : Prisma.GetScalarType<T[P], AggregateOfficialTranslationWord[P]>
}




export type OfficialTranslationWordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfficialTranslationWordWhereInput
  orderBy?: Prisma.OfficialTranslationWordOrderByWithAggregationInput | Prisma.OfficialTranslationWordOrderByWithAggregationInput[]
  by: Prisma.OfficialTranslationWordScalarFieldEnum[] | Prisma.OfficialTranslationWordScalarFieldEnum
  having?: Prisma.OfficialTranslationWordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OfficialTranslationWordCountAggregateInputType | true
  _min?: OfficialTranslationWordMinAggregateInputType
  _max?: OfficialTranslationWordMaxAggregateInputType
}

export type OfficialTranslationWordGroupByOutputType = {
  id: string
  text: string
  language: string
  note: string | null
  wordId: string
  createdAt: Date
  updatedAt: Date
  _count: OfficialTranslationWordCountAggregateOutputType | null
  _min: OfficialTranslationWordMinAggregateOutputType | null
  _max: OfficialTranslationWordMaxAggregateOutputType | null
}

export type GetOfficialTranslationWordGroupByPayload<T extends OfficialTranslationWordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OfficialTranslationWordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OfficialTranslationWordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OfficialTranslationWordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OfficialTranslationWordGroupByOutputType[P]>
      }
    >
  >



export type OfficialTranslationWordWhereInput = {
  AND?: Prisma.OfficialTranslationWordWhereInput | Prisma.OfficialTranslationWordWhereInput[]
  OR?: Prisma.OfficialTranslationWordWhereInput[]
  NOT?: Prisma.OfficialTranslationWordWhereInput | Prisma.OfficialTranslationWordWhereInput[]
  id?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  text?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  language?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  note?: Prisma.StringNullableFilter<"OfficialTranslationWord"> | string | null
  wordId?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialTranslationWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialTranslationWord"> | Date | string
  word?: Prisma.XOR<Prisma.OfficialWordScalarRelationFilter, Prisma.OfficialWordWhereInput>
}

export type OfficialTranslationWordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  word?: Prisma.OfficialWordOrderByWithRelationInput
}

export type OfficialTranslationWordWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  wordId_language?: Prisma.OfficialTranslationWordWordIdLanguageCompoundUniqueInput
  AND?: Prisma.OfficialTranslationWordWhereInput | Prisma.OfficialTranslationWordWhereInput[]
  OR?: Prisma.OfficialTranslationWordWhereInput[]
  NOT?: Prisma.OfficialTranslationWordWhereInput | Prisma.OfficialTranslationWordWhereInput[]
  text?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  language?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  note?: Prisma.StringNullableFilter<"OfficialTranslationWord"> | string | null
  wordId?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialTranslationWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialTranslationWord"> | Date | string
  word?: Prisma.XOR<Prisma.OfficialWordScalarRelationFilter, Prisma.OfficialWordWhereInput>
}, "id" | "wordId_language">

export type OfficialTranslationWordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OfficialTranslationWordCountOrderByAggregateInput
  _max?: Prisma.OfficialTranslationWordMaxOrderByAggregateInput
  _min?: Prisma.OfficialTranslationWordMinOrderByAggregateInput
}

export type OfficialTranslationWordScalarWhereWithAggregatesInput = {
  AND?: Prisma.OfficialTranslationWordScalarWhereWithAggregatesInput | Prisma.OfficialTranslationWordScalarWhereWithAggregatesInput[]
  OR?: Prisma.OfficialTranslationWordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OfficialTranslationWordScalarWhereWithAggregatesInput | Prisma.OfficialTranslationWordScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OfficialTranslationWord"> | string
  text?: Prisma.StringWithAggregatesFilter<"OfficialTranslationWord"> | string
  language?: Prisma.StringWithAggregatesFilter<"OfficialTranslationWord"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"OfficialTranslationWord"> | string | null
  wordId?: Prisma.StringWithAggregatesFilter<"OfficialTranslationWord"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OfficialTranslationWord"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OfficialTranslationWord"> | Date | string
}

export type OfficialTranslationWordCreateInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  word: Prisma.OfficialWordCreateNestedOneWithoutTranslationsInput
}

export type OfficialTranslationWordUncheckedCreateInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  wordId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationWordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  word?: Prisma.OfficialWordUpdateOneRequiredWithoutTranslationsNestedInput
}

export type OfficialTranslationWordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wordId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationWordCreateManyInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  wordId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationWordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationWordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wordId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationWordListRelationFilter = {
  every?: Prisma.OfficialTranslationWordWhereInput
  some?: Prisma.OfficialTranslationWordWhereInput
  none?: Prisma.OfficialTranslationWordWhereInput
}

export type OfficialTranslationWordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OfficialTranslationWordWordIdLanguageCompoundUniqueInput = {
  wordId: string
  language: string
}

export type OfficialTranslationWordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialTranslationWordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialTranslationWordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialTranslationWordCreateNestedManyWithoutWordInput = {
  create?: Prisma.XOR<Prisma.OfficialTranslationWordCreateWithoutWordInput, Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput> | Prisma.OfficialTranslationWordCreateWithoutWordInput[] | Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput[]
  connectOrCreate?: Prisma.OfficialTranslationWordCreateOrConnectWithoutWordInput | Prisma.OfficialTranslationWordCreateOrConnectWithoutWordInput[]
  createMany?: Prisma.OfficialTranslationWordCreateManyWordInputEnvelope
  connect?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
}

export type OfficialTranslationWordUncheckedCreateNestedManyWithoutWordInput = {
  create?: Prisma.XOR<Prisma.OfficialTranslationWordCreateWithoutWordInput, Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput> | Prisma.OfficialTranslationWordCreateWithoutWordInput[] | Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput[]
  connectOrCreate?: Prisma.OfficialTranslationWordCreateOrConnectWithoutWordInput | Prisma.OfficialTranslationWordCreateOrConnectWithoutWordInput[]
  createMany?: Prisma.OfficialTranslationWordCreateManyWordInputEnvelope
  connect?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
}

export type OfficialTranslationWordUpdateManyWithoutWordNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialTranslationWordCreateWithoutWordInput, Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput> | Prisma.OfficialTranslationWordCreateWithoutWordInput[] | Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput[]
  connectOrCreate?: Prisma.OfficialTranslationWordCreateOrConnectWithoutWordInput | Prisma.OfficialTranslationWordCreateOrConnectWithoutWordInput[]
  upsert?: Prisma.OfficialTranslationWordUpsertWithWhereUniqueWithoutWordInput | Prisma.OfficialTranslationWordUpsertWithWhereUniqueWithoutWordInput[]
  createMany?: Prisma.OfficialTranslationWordCreateManyWordInputEnvelope
  set?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
  disconnect?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
  delete?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
  connect?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
  update?: Prisma.OfficialTranslationWordUpdateWithWhereUniqueWithoutWordInput | Prisma.OfficialTranslationWordUpdateWithWhereUniqueWithoutWordInput[]
  updateMany?: Prisma.OfficialTranslationWordUpdateManyWithWhereWithoutWordInput | Prisma.OfficialTranslationWordUpdateManyWithWhereWithoutWordInput[]
  deleteMany?: Prisma.OfficialTranslationWordScalarWhereInput | Prisma.OfficialTranslationWordScalarWhereInput[]
}

export type OfficialTranslationWordUncheckedUpdateManyWithoutWordNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialTranslationWordCreateWithoutWordInput, Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput> | Prisma.OfficialTranslationWordCreateWithoutWordInput[] | Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput[]
  connectOrCreate?: Prisma.OfficialTranslationWordCreateOrConnectWithoutWordInput | Prisma.OfficialTranslationWordCreateOrConnectWithoutWordInput[]
  upsert?: Prisma.OfficialTranslationWordUpsertWithWhereUniqueWithoutWordInput | Prisma.OfficialTranslationWordUpsertWithWhereUniqueWithoutWordInput[]
  createMany?: Prisma.OfficialTranslationWordCreateManyWordInputEnvelope
  set?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
  disconnect?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
  delete?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
  connect?: Prisma.OfficialTranslationWordWhereUniqueInput | Prisma.OfficialTranslationWordWhereUniqueInput[]
  update?: Prisma.OfficialTranslationWordUpdateWithWhereUniqueWithoutWordInput | Prisma.OfficialTranslationWordUpdateWithWhereUniqueWithoutWordInput[]
  updateMany?: Prisma.OfficialTranslationWordUpdateManyWithWhereWithoutWordInput | Prisma.OfficialTranslationWordUpdateManyWithWhereWithoutWordInput[]
  deleteMany?: Prisma.OfficialTranslationWordScalarWhereInput | Prisma.OfficialTranslationWordScalarWhereInput[]
}

export type OfficialTranslationWordCreateWithoutWordInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationWordUncheckedCreateWithoutWordInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationWordCreateOrConnectWithoutWordInput = {
  where: Prisma.OfficialTranslationWordWhereUniqueInput
  create: Prisma.XOR<Prisma.OfficialTranslationWordCreateWithoutWordInput, Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput>
}

export type OfficialTranslationWordCreateManyWordInputEnvelope = {
  data: Prisma.OfficialTranslationWordCreateManyWordInput | Prisma.OfficialTranslationWordCreateManyWordInput[]
  skipDuplicates?: boolean
}

export type OfficialTranslationWordUpsertWithWhereUniqueWithoutWordInput = {
  where: Prisma.OfficialTranslationWordWhereUniqueInput
  update: Prisma.XOR<Prisma.OfficialTranslationWordUpdateWithoutWordInput, Prisma.OfficialTranslationWordUncheckedUpdateWithoutWordInput>
  create: Prisma.XOR<Prisma.OfficialTranslationWordCreateWithoutWordInput, Prisma.OfficialTranslationWordUncheckedCreateWithoutWordInput>
}

export type OfficialTranslationWordUpdateWithWhereUniqueWithoutWordInput = {
  where: Prisma.OfficialTranslationWordWhereUniqueInput
  data: Prisma.XOR<Prisma.OfficialTranslationWordUpdateWithoutWordInput, Prisma.OfficialTranslationWordUncheckedUpdateWithoutWordInput>
}

export type OfficialTranslationWordUpdateManyWithWhereWithoutWordInput = {
  where: Prisma.OfficialTranslationWordScalarWhereInput
  data: Prisma.XOR<Prisma.OfficialTranslationWordUpdateManyMutationInput, Prisma.OfficialTranslationWordUncheckedUpdateManyWithoutWordInput>
}

export type OfficialTranslationWordScalarWhereInput = {
  AND?: Prisma.OfficialTranslationWordScalarWhereInput | Prisma.OfficialTranslationWordScalarWhereInput[]
  OR?: Prisma.OfficialTranslationWordScalarWhereInput[]
  NOT?: Prisma.OfficialTranslationWordScalarWhereInput | Prisma.OfficialTranslationWordScalarWhereInput[]
  id?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  text?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  language?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  note?: Prisma.StringNullableFilter<"OfficialTranslationWord"> | string | null
  wordId?: Prisma.StringFilter<"OfficialTranslationWord"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialTranslationWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialTranslationWord"> | Date | string
}

export type OfficialTranslationWordCreateManyWordInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationWordUpdateWithoutWordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationWordUncheckedUpdateWithoutWordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationWordUncheckedUpdateManyWithoutWordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type OfficialTranslationWordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  wordId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  word?: boolean | Prisma.OfficialWordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialTranslationWord"]>

export type OfficialTranslationWordSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  wordId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  word?: boolean | Prisma.OfficialWordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialTranslationWord"]>

export type OfficialTranslationWordSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  wordId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  word?: boolean | Prisma.OfficialWordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialTranslationWord"]>

export type OfficialTranslationWordSelectScalar = {
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  wordId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OfficialTranslationWordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "text" | "language" | "note" | "wordId" | "createdAt" | "updatedAt", ExtArgs["result"]["officialTranslationWord"]>
export type OfficialTranslationWordInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  word?: boolean | Prisma.OfficialWordDefaultArgs<ExtArgs>
}
export type OfficialTranslationWordIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  word?: boolean | Prisma.OfficialWordDefaultArgs<ExtArgs>
}
export type OfficialTranslationWordIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  word?: boolean | Prisma.OfficialWordDefaultArgs<ExtArgs>
}

export type $OfficialTranslationWordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OfficialTranslationWord"
  objects: {
    word: Prisma.$OfficialWordPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    text: string
    language: string
    note: string | null
    wordId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["officialTranslationWord"]>
  composites: {}
}

export type OfficialTranslationWordGetPayload<S extends boolean | null | undefined | OfficialTranslationWordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload, S>

export type OfficialTranslationWordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OfficialTranslationWordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OfficialTranslationWordCountAggregateInputType | true
  }

export interface OfficialTranslationWordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OfficialTranslationWord'], meta: { name: 'OfficialTranslationWord' } }
  /**
   * Find zero or one OfficialTranslationWord that matches the filter.
   * @param {OfficialTranslationWordFindUniqueArgs} args - Arguments to find a OfficialTranslationWord
   * @example
   * // Get one OfficialTranslationWord
   * const officialTranslationWord = await prisma.officialTranslationWord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OfficialTranslationWordFindUniqueArgs>(args: Prisma.SelectSubset<T, OfficialTranslationWordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OfficialTranslationWord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OfficialTranslationWordFindUniqueOrThrowArgs} args - Arguments to find a OfficialTranslationWord
   * @example
   * // Get one OfficialTranslationWord
   * const officialTranslationWord = await prisma.officialTranslationWord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OfficialTranslationWordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OfficialTranslationWordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfficialTranslationWord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationWordFindFirstArgs} args - Arguments to find a OfficialTranslationWord
   * @example
   * // Get one OfficialTranslationWord
   * const officialTranslationWord = await prisma.officialTranslationWord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OfficialTranslationWordFindFirstArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationWordFindFirstArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfficialTranslationWord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationWordFindFirstOrThrowArgs} args - Arguments to find a OfficialTranslationWord
   * @example
   * // Get one OfficialTranslationWord
   * const officialTranslationWord = await prisma.officialTranslationWord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OfficialTranslationWordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationWordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OfficialTranslationWords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationWordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OfficialTranslationWords
   * const officialTranslationWords = await prisma.officialTranslationWord.findMany()
   *
   * // Get first 10 OfficialTranslationWords
   * const officialTranslationWords = await prisma.officialTranslationWord.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const officialTranslationWordWithIdOnly = await prisma.officialTranslationWord.findMany({ select: { id: true } })
   *
   */
  findMany<T extends OfficialTranslationWordFindManyArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationWordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OfficialTranslationWord.
   * @param {OfficialTranslationWordCreateArgs} args - Arguments to create a OfficialTranslationWord.
   * @example
   * // Create one OfficialTranslationWord
   * const OfficialTranslationWord = await prisma.officialTranslationWord.create({
   *   data: {
   *     // ... data to create a OfficialTranslationWord
   *   }
   * })
   *
   */
  create<T extends OfficialTranslationWordCreateArgs>(args: Prisma.SelectSubset<T, OfficialTranslationWordCreateArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OfficialTranslationWords.
   * @param {OfficialTranslationWordCreateManyArgs} args - Arguments to create many OfficialTranslationWords.
   * @example
   * // Create many OfficialTranslationWords
   * const officialTranslationWord = await prisma.officialTranslationWord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends OfficialTranslationWordCreateManyArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationWordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OfficialTranslationWords and returns the data saved in the database.
   * @param {OfficialTranslationWordCreateManyAndReturnArgs} args - Arguments to create many OfficialTranslationWords.
   * @example
   * // Create many OfficialTranslationWords
   * const officialTranslationWord = await prisma.officialTranslationWord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many OfficialTranslationWords and only return the `id`
   * const officialTranslationWordWithIdOnly = await prisma.officialTranslationWord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends OfficialTranslationWordCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationWordCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OfficialTranslationWord.
   * @param {OfficialTranslationWordDeleteArgs} args - Arguments to delete one OfficialTranslationWord.
   * @example
   * // Delete one OfficialTranslationWord
   * const OfficialTranslationWord = await prisma.officialTranslationWord.delete({
   *   where: {
   *     // ... filter to delete one OfficialTranslationWord
   *   }
   * })
   *
   */
  delete<T extends OfficialTranslationWordDeleteArgs>(args: Prisma.SelectSubset<T, OfficialTranslationWordDeleteArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OfficialTranslationWord.
   * @param {OfficialTranslationWordUpdateArgs} args - Arguments to update one OfficialTranslationWord.
   * @example
   * // Update one OfficialTranslationWord
   * const officialTranslationWord = await prisma.officialTranslationWord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends OfficialTranslationWordUpdateArgs>(args: Prisma.SelectSubset<T, OfficialTranslationWordUpdateArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OfficialTranslationWords.
   * @param {OfficialTranslationWordDeleteManyArgs} args - Arguments to filter OfficialTranslationWords to delete.
   * @example
   * // Delete a few OfficialTranslationWords
   * const { count } = await prisma.officialTranslationWord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends OfficialTranslationWordDeleteManyArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationWordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfficialTranslationWords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationWordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OfficialTranslationWords
   * const officialTranslationWord = await prisma.officialTranslationWord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends OfficialTranslationWordUpdateManyArgs>(args: Prisma.SelectSubset<T, OfficialTranslationWordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfficialTranslationWords and returns the data updated in the database.
   * @param {OfficialTranslationWordUpdateManyAndReturnArgs} args - Arguments to update many OfficialTranslationWords.
   * @example
   * // Update many OfficialTranslationWords
   * const officialTranslationWord = await prisma.officialTranslationWord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more OfficialTranslationWords and only return the `id`
   * const officialTranslationWordWithIdOnly = await prisma.officialTranslationWord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends OfficialTranslationWordUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OfficialTranslationWordUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OfficialTranslationWord.
   * @param {OfficialTranslationWordUpsertArgs} args - Arguments to update or create a OfficialTranslationWord.
   * @example
   * // Update or create a OfficialTranslationWord
   * const officialTranslationWord = await prisma.officialTranslationWord.upsert({
   *   create: {
   *     // ... data to create a OfficialTranslationWord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OfficialTranslationWord we want to update
   *   }
   * })
   */
  upsert<T extends OfficialTranslationWordUpsertArgs>(args: Prisma.SelectSubset<T, OfficialTranslationWordUpsertArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OfficialTranslationWords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationWordCountArgs} args - Arguments to filter OfficialTranslationWords to count.
   * @example
   * // Count the number of OfficialTranslationWords
   * const count = await prisma.officialTranslationWord.count({
   *   where: {
   *     // ... the filter for the OfficialTranslationWords we want to count
   *   }
   * })
  **/
  count<T extends OfficialTranslationWordCountArgs>(
    args?: Prisma.Subset<T, OfficialTranslationWordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OfficialTranslationWordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OfficialTranslationWord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationWordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OfficialTranslationWordAggregateArgs>(args: Prisma.Subset<T, OfficialTranslationWordAggregateArgs>): Prisma.PrismaPromise<GetOfficialTranslationWordAggregateType<T>>

  /**
   * Group by OfficialTranslationWord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationWordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
  **/
  groupBy<
    T extends OfficialTranslationWordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OfficialTranslationWordGroupByArgs['orderBy'] }
      : { orderBy?: OfficialTranslationWordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OfficialTranslationWordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOfficialTranslationWordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OfficialTranslationWord model
 */
readonly fields: OfficialTranslationWordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OfficialTranslationWord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OfficialTranslationWordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  word<T extends Prisma.OfficialWordDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfficialWordDefaultArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OfficialTranslationWord model
 */
export interface OfficialTranslationWordFieldRefs {
  readonly id: Prisma.FieldRef<"OfficialTranslationWord", 'String'>
  readonly text: Prisma.FieldRef<"OfficialTranslationWord", 'String'>
  readonly language: Prisma.FieldRef<"OfficialTranslationWord", 'String'>
  readonly note: Prisma.FieldRef<"OfficialTranslationWord", 'String'>
  readonly wordId: Prisma.FieldRef<"OfficialTranslationWord", 'String'>
  readonly createdAt: Prisma.FieldRef<"OfficialTranslationWord", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OfficialTranslationWord", 'DateTime'>
}


// Custom InputTypes
/**
 * OfficialTranslationWord findUnique
 */
export type OfficialTranslationWordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationWord to fetch.
   */
  where: Prisma.OfficialTranslationWordWhereUniqueInput
}

/**
 * OfficialTranslationWord findUniqueOrThrow
 */
export type OfficialTranslationWordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationWord to fetch.
   */
  where: Prisma.OfficialTranslationWordWhereUniqueInput
}

/**
 * OfficialTranslationWord findFirst
 */
export type OfficialTranslationWordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationWord to fetch.
   */
  where?: Prisma.OfficialTranslationWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialTranslationWords to fetch.
   */
  orderBy?: Prisma.OfficialTranslationWordOrderByWithRelationInput | Prisma.OfficialTranslationWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OfficialTranslationWords.
   */
  cursor?: Prisma.OfficialTranslationWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialTranslationWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialTranslationWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialTranslationWords.
   */
  distinct?: Prisma.OfficialTranslationWordScalarFieldEnum | Prisma.OfficialTranslationWordScalarFieldEnum[]
}

/**
 * OfficialTranslationWord findFirstOrThrow
 */
export type OfficialTranslationWordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationWord to fetch.
   */
  where?: Prisma.OfficialTranslationWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialTranslationWords to fetch.
   */
  orderBy?: Prisma.OfficialTranslationWordOrderByWithRelationInput | Prisma.OfficialTranslationWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OfficialTranslationWords.
   */
  cursor?: Prisma.OfficialTranslationWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialTranslationWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialTranslationWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialTranslationWords.
   */
  distinct?: Prisma.OfficialTranslationWordScalarFieldEnum | Prisma.OfficialTranslationWordScalarFieldEnum[]
}

/**
 * OfficialTranslationWord findMany
 */
export type OfficialTranslationWordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationWords to fetch.
   */
  where?: Prisma.OfficialTranslationWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialTranslationWords to fetch.
   */
  orderBy?: Prisma.OfficialTranslationWordOrderByWithRelationInput | Prisma.OfficialTranslationWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing OfficialTranslationWords.
   */
  cursor?: Prisma.OfficialTranslationWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialTranslationWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialTranslationWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialTranslationWords.
   */
  distinct?: Prisma.OfficialTranslationWordScalarFieldEnum | Prisma.OfficialTranslationWordScalarFieldEnum[]
}

/**
 * OfficialTranslationWord create
 */
export type OfficialTranslationWordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * The data needed to create a OfficialTranslationWord.
   */
  data: Prisma.XOR<Prisma.OfficialTranslationWordCreateInput, Prisma.OfficialTranslationWordUncheckedCreateInput>
}

/**
 * OfficialTranslationWord createMany
 */
export type OfficialTranslationWordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OfficialTranslationWords.
   */
  data: Prisma.OfficialTranslationWordCreateManyInput | Prisma.OfficialTranslationWordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OfficialTranslationWord createManyAndReturn
 */
export type OfficialTranslationWordCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * The data used to create many OfficialTranslationWords.
   */
  data: Prisma.OfficialTranslationWordCreateManyInput | Prisma.OfficialTranslationWordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OfficialTranslationWord update
 */
export type OfficialTranslationWordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * The data needed to update a OfficialTranslationWord.
   */
  data: Prisma.XOR<Prisma.OfficialTranslationWordUpdateInput, Prisma.OfficialTranslationWordUncheckedUpdateInput>
  /**
   * Choose, which OfficialTranslationWord to update.
   */
  where: Prisma.OfficialTranslationWordWhereUniqueInput
}

/**
 * OfficialTranslationWord updateMany
 */
export type OfficialTranslationWordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OfficialTranslationWords.
   */
  data: Prisma.XOR<Prisma.OfficialTranslationWordUpdateManyMutationInput, Prisma.OfficialTranslationWordUncheckedUpdateManyInput>
  /**
   * Filter which OfficialTranslationWords to update
   */
  where?: Prisma.OfficialTranslationWordWhereInput
  /**
   * Limit how many OfficialTranslationWords to update.
   */
  limit?: number
}

/**
 * OfficialTranslationWord updateManyAndReturn
 */
export type OfficialTranslationWordUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * The data used to update OfficialTranslationWords.
   */
  data: Prisma.XOR<Prisma.OfficialTranslationWordUpdateManyMutationInput, Prisma.OfficialTranslationWordUncheckedUpdateManyInput>
  /**
   * Filter which OfficialTranslationWords to update
   */
  where?: Prisma.OfficialTranslationWordWhereInput
  /**
   * Limit how many OfficialTranslationWords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OfficialTranslationWord upsert
 */
export type OfficialTranslationWordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * The filter to search for the OfficialTranslationWord to update in case it exists.
   */
  where: Prisma.OfficialTranslationWordWhereUniqueInput
  /**
   * In case the OfficialTranslationWord found by the `where` argument doesn't exist, create a new OfficialTranslationWord with this data.
   */
  create: Prisma.XOR<Prisma.OfficialTranslationWordCreateInput, Prisma.OfficialTranslationWordUncheckedCreateInput>
  /**
   * In case the OfficialTranslationWord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OfficialTranslationWordUpdateInput, Prisma.OfficialTranslationWordUncheckedUpdateInput>
}

/**
 * OfficialTranslationWord delete
 */
export type OfficialTranslationWordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  /**
   * Filter which OfficialTranslationWord to delete.
   */
  where: Prisma.OfficialTranslationWordWhereUniqueInput
}

/**
 * OfficialTranslationWord deleteMany
 */
export type OfficialTranslationWordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfficialTranslationWords to delete
   */
  where?: Prisma.OfficialTranslationWordWhereInput
  /**
   * Limit how many OfficialTranslationWords to delete.
   */
  limit?: number
}

/**
 * OfficialTranslationWord without action
 */
export type OfficialTranslationWordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
}
