
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `OfficialList` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OfficialList
 *
 */
export type OfficialListModel = runtime.Types.Result.DefaultSelection<Prisma.$OfficialListPayload>

export type AggregateOfficialList = {
  _count: OfficialListCountAggregateOutputType | null
  _min: OfficialListMinAggregateOutputType | null
  _max: OfficialListMaxAggregateOutputType | null
}

export type OfficialListMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  language: string | null
  published: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OfficialListMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  language: string | null
  published: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OfficialListCountAggregateOutputType = {
  id: number
  name: number
  description: number
  language: number
  published: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OfficialListMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  language?: true
  published?: true
  createdAt?: true
  updatedAt?: true
}

export type OfficialListMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  language?: true
  published?: true
  createdAt?: true
  updatedAt?: true
}

export type OfficialListCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  language?: true
  published?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OfficialListAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfficialList to aggregate.
   */
  where?: Prisma.OfficialListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialLists to fetch.
   */
  orderBy?: Prisma.OfficialListOrderByWithRelationInput | Prisma.OfficialListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.OfficialListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned OfficialLists
  **/
  _count?: true | OfficialListCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
  **/
  _min?: OfficialListMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
  **/
  _max?: OfficialListMaxAggregateInputType
}

export type GetOfficialListAggregateType<T extends OfficialListAggregateArgs> = {
      [P in keyof T & keyof AggregateOfficialList]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOfficialList[P]>
    : Prisma.GetScalarType<T[P], AggregateOfficialList[P]>
}




export type OfficialListGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfficialListWhereInput
  orderBy?: Prisma.OfficialListOrderByWithAggregationInput | Prisma.OfficialListOrderByWithAggregationInput[]
  by: Prisma.OfficialListScalarFieldEnum[] | Prisma.OfficialListScalarFieldEnum
  having?: Prisma.OfficialListScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OfficialListCountAggregateInputType | true
  _min?: OfficialListMinAggregateInputType
  _max?: OfficialListMaxAggregateInputType
}

export type OfficialListGroupByOutputType = {
  id: string
  name: string
  description: string | null
  language: string
  published: boolean
  createdAt: Date
  updatedAt: Date
  _count: OfficialListCountAggregateOutputType | null
  _min: OfficialListMinAggregateOutputType | null
  _max: OfficialListMaxAggregateOutputType | null
}

export type GetOfficialListGroupByPayload<T extends OfficialListGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OfficialListGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OfficialListGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OfficialListGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OfficialListGroupByOutputType[P]>
      }
    >
  >



export type OfficialListWhereInput = {
  AND?: Prisma.OfficialListWhereInput | Prisma.OfficialListWhereInput[]
  OR?: Prisma.OfficialListWhereInput[]
  NOT?: Prisma.OfficialListWhereInput | Prisma.OfficialListWhereInput[]
  id?: Prisma.StringFilter<"OfficialList"> | string
  name?: Prisma.StringFilter<"OfficialList"> | string
  description?: Prisma.StringNullableFilter<"OfficialList"> | string | null
  language?: Prisma.StringFilter<"OfficialList"> | string
  published?: Prisma.BoolFilter<"OfficialList"> | boolean
  createdAt?: Prisma.DateTimeFilter<"OfficialList"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialList"> | Date | string
  words?: Prisma.OfficialWordListRelationFilter
  translationLanguages?: Prisma.OfficialTranslationListListRelationFilter
}

export type OfficialListOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  words?: Prisma.OfficialWordOrderByRelationAggregateInput
  translationLanguages?: Prisma.OfficialTranslationListOrderByRelationAggregateInput
}

export type OfficialListWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.OfficialListWhereInput | Prisma.OfficialListWhereInput[]
  OR?: Prisma.OfficialListWhereInput[]
  NOT?: Prisma.OfficialListWhereInput | Prisma.OfficialListWhereInput[]
  name?: Prisma.StringFilter<"OfficialList"> | string
  description?: Prisma.StringNullableFilter<"OfficialList"> | string | null
  language?: Prisma.StringFilter<"OfficialList"> | string
  published?: Prisma.BoolFilter<"OfficialList"> | boolean
  createdAt?: Prisma.DateTimeFilter<"OfficialList"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialList"> | Date | string
  words?: Prisma.OfficialWordListRelationFilter
  translationLanguages?: Prisma.OfficialTranslationListListRelationFilter
}, "id">

export type OfficialListOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  language?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OfficialListCountOrderByAggregateInput
  _max?: Prisma.OfficialListMaxOrderByAggregateInput
  _min?: Prisma.OfficialListMinOrderByAggregateInput
}

export type OfficialListScalarWhereWithAggregatesInput = {
  AND?: Prisma.OfficialListScalarWhereWithAggregatesInput | Prisma.OfficialListScalarWhereWithAggregatesInput[]
  OR?: Prisma.OfficialListScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OfficialListScalarWhereWithAggregatesInput | Prisma.OfficialListScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OfficialList"> | string
  name?: Prisma.StringWithAggregatesFilter<"OfficialList"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"OfficialList"> | string | null
  language?: Prisma.StringWithAggregatesFilter<"OfficialList"> | string
  published?: Prisma.BoolWithAggregatesFilter<"OfficialList"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OfficialList"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OfficialList"> | Date | string
}

export type OfficialListCreateInput = {
  id?: string
  name: string
  description?: string | null
  language: string
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  words?: Prisma.OfficialWordCreateNestedManyWithoutListInput
  translationLanguages?: Prisma.OfficialTranslationListCreateNestedManyWithoutListInput
}

export type OfficialListUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  language: string
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  words?: Prisma.OfficialWordUncheckedCreateNestedManyWithoutListInput
  translationLanguages?: Prisma.OfficialTranslationListUncheckedCreateNestedManyWithoutListInput
}

export type OfficialListUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  words?: Prisma.OfficialWordUpdateManyWithoutListNestedInput
  translationLanguages?: Prisma.OfficialTranslationListUpdateManyWithoutListNestedInput
}

export type OfficialListUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  words?: Prisma.OfficialWordUncheckedUpdateManyWithoutListNestedInput
  translationLanguages?: Prisma.OfficialTranslationListUncheckedUpdateManyWithoutListNestedInput
}

export type OfficialListCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  language: string
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialListUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialListUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialListCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  language?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialListMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  language?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialListMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  language?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialListScalarRelationFilter = {
  is?: Prisma.OfficialListWhereInput
  isNot?: Prisma.OfficialListWhereInput
}

export type OfficialListCreateNestedOneWithoutWordsInput = {
  create?: Prisma.XOR<Prisma.OfficialListCreateWithoutWordsInput, Prisma.OfficialListUncheckedCreateWithoutWordsInput>
  connectOrCreate?: Prisma.OfficialListCreateOrConnectWithoutWordsInput
  connect?: Prisma.OfficialListWhereUniqueInput
}

export type OfficialListUpdateOneRequiredWithoutWordsNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialListCreateWithoutWordsInput, Prisma.OfficialListUncheckedCreateWithoutWordsInput>
  connectOrCreate?: Prisma.OfficialListCreateOrConnectWithoutWordsInput
  upsert?: Prisma.OfficialListUpsertWithoutWordsInput
  connect?: Prisma.OfficialListWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OfficialListUpdateToOneWithWhereWithoutWordsInput, Prisma.OfficialListUpdateWithoutWordsInput>, Prisma.OfficialListUncheckedUpdateWithoutWordsInput>
}

export type OfficialListCreateNestedOneWithoutTranslationLanguagesInput = {
  create?: Prisma.XOR<Prisma.OfficialListCreateWithoutTranslationLanguagesInput, Prisma.OfficialListUncheckedCreateWithoutTranslationLanguagesInput>
  connectOrCreate?: Prisma.OfficialListCreateOrConnectWithoutTranslationLanguagesInput
  connect?: Prisma.OfficialListWhereUniqueInput
}

export type OfficialListUpdateOneRequiredWithoutTranslationLanguagesNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialListCreateWithoutTranslationLanguagesInput, Prisma.OfficialListUncheckedCreateWithoutTranslationLanguagesInput>
  connectOrCreate?: Prisma.OfficialListCreateOrConnectWithoutTranslationLanguagesInput
  upsert?: Prisma.OfficialListUpsertWithoutTranslationLanguagesInput
  connect?: Prisma.OfficialListWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OfficialListUpdateToOneWithWhereWithoutTranslationLanguagesInput, Prisma.OfficialListUpdateWithoutTranslationLanguagesInput>, Prisma.OfficialListUncheckedUpdateWithoutTranslationLanguagesInput>
}

export type OfficialListCreateWithoutWordsInput = {
  id?: string
  name: string
  description?: string | null
  language: string
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  translationLanguages?: Prisma.OfficialTranslationListCreateNestedManyWithoutListInput
}

export type OfficialListUncheckedCreateWithoutWordsInput = {
  id?: string
  name: string
  description?: string | null
  language: string
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  translationLanguages?: Prisma.OfficialTranslationListUncheckedCreateNestedManyWithoutListInput
}

export type OfficialListCreateOrConnectWithoutWordsInput = {
  where: Prisma.OfficialListWhereUniqueInput
  create: Prisma.XOR<Prisma.OfficialListCreateWithoutWordsInput, Prisma.OfficialListUncheckedCreateWithoutWordsInput>
}

export type OfficialListUpsertWithoutWordsInput = {
  update: Prisma.XOR<Prisma.OfficialListUpdateWithoutWordsInput, Prisma.OfficialListUncheckedUpdateWithoutWordsInput>
  create: Prisma.XOR<Prisma.OfficialListCreateWithoutWordsInput, Prisma.OfficialListUncheckedCreateWithoutWordsInput>
  where?: Prisma.OfficialListWhereInput
}

export type OfficialListUpdateToOneWithWhereWithoutWordsInput = {
  where?: Prisma.OfficialListWhereInput
  data: Prisma.XOR<Prisma.OfficialListUpdateWithoutWordsInput, Prisma.OfficialListUncheckedUpdateWithoutWordsInput>
}

export type OfficialListUpdateWithoutWordsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  translationLanguages?: Prisma.OfficialTranslationListUpdateManyWithoutListNestedInput
}

export type OfficialListUncheckedUpdateWithoutWordsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  translationLanguages?: Prisma.OfficialTranslationListUncheckedUpdateManyWithoutListNestedInput
}

export type OfficialListCreateWithoutTranslationLanguagesInput = {
  id?: string
  name: string
  description?: string | null
  language: string
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  words?: Prisma.OfficialWordCreateNestedManyWithoutListInput
}

export type OfficialListUncheckedCreateWithoutTranslationLanguagesInput = {
  id?: string
  name: string
  description?: string | null
  language: string
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  words?: Prisma.OfficialWordUncheckedCreateNestedManyWithoutListInput
}

export type OfficialListCreateOrConnectWithoutTranslationLanguagesInput = {
  where: Prisma.OfficialListWhereUniqueInput
  create: Prisma.XOR<Prisma.OfficialListCreateWithoutTranslationLanguagesInput, Prisma.OfficialListUncheckedCreateWithoutTranslationLanguagesInput>
}

export type OfficialListUpsertWithoutTranslationLanguagesInput = {
  update: Prisma.XOR<Prisma.OfficialListUpdateWithoutTranslationLanguagesInput, Prisma.OfficialListUncheckedUpdateWithoutTranslationLanguagesInput>
  create: Prisma.XOR<Prisma.OfficialListCreateWithoutTranslationLanguagesInput, Prisma.OfficialListUncheckedCreateWithoutTranslationLanguagesInput>
  where?: Prisma.OfficialListWhereInput
}

export type OfficialListUpdateToOneWithWhereWithoutTranslationLanguagesInput = {
  where?: Prisma.OfficialListWhereInput
  data: Prisma.XOR<Prisma.OfficialListUpdateWithoutTranslationLanguagesInput, Prisma.OfficialListUncheckedUpdateWithoutTranslationLanguagesInput>
}

export type OfficialListUpdateWithoutTranslationLanguagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  words?: Prisma.OfficialWordUpdateManyWithoutListNestedInput
}

export type OfficialListUncheckedUpdateWithoutTranslationLanguagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  language?: Prisma.StringFieldUpdateOperationsInput | string
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  words?: Prisma.OfficialWordUncheckedUpdateManyWithoutListNestedInput
}


/**
 * Count Type OfficialListCountOutputType
 */

export type OfficialListCountOutputType = {
  words: number
  translationLanguages: number
}

export type OfficialListCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  words?: boolean | OfficialListCountOutputTypeCountWordsArgs
  translationLanguages?: boolean | OfficialListCountOutputTypeCountTranslationLanguagesArgs
}

/**
 * OfficialListCountOutputType without action
 */
export type OfficialListCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialListCountOutputType
   */
  select?: Prisma.OfficialListCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OfficialListCountOutputType without action
 */
export type OfficialListCountOutputTypeCountWordsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfficialWordWhereInput
}

/**
 * OfficialListCountOutputType without action
 */
export type OfficialListCountOutputTypeCountTranslationLanguagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfficialTranslationListWhereInput
}


export type OfficialListSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  language?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  words?: boolean | Prisma.OfficialList$wordsArgs<ExtArgs>
  translationLanguages?: boolean | Prisma.OfficialList$translationLanguagesArgs<ExtArgs>
  _count?: boolean | Prisma.OfficialListCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialList"]>

export type OfficialListSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  language?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["officialList"]>

export type OfficialListSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  language?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["officialList"]>

export type OfficialListSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  language?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OfficialListOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "language" | "published" | "createdAt" | "updatedAt", ExtArgs["result"]["officialList"]>
export type OfficialListInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  words?: boolean | Prisma.OfficialList$wordsArgs<ExtArgs>
  translationLanguages?: boolean | Prisma.OfficialList$translationLanguagesArgs<ExtArgs>
  _count?: boolean | Prisma.OfficialListCountOutputTypeDefaultArgs<ExtArgs>
}
export type OfficialListIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type OfficialListIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $OfficialListPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OfficialList"
  objects: {
    words: Prisma.$OfficialWordPayload<ExtArgs>[]
    translationLanguages: Prisma.$OfficialTranslationListPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    language: string
    published: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["officialList"]>
  composites: {}
}

export type OfficialListGetPayload<S extends boolean | null | undefined | OfficialListDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OfficialListPayload, S>

export type OfficialListCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OfficialListFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OfficialListCountAggregateInputType | true
  }

export interface OfficialListDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OfficialList'], meta: { name: 'OfficialList' } }
  /**
   * Find zero or one OfficialList that matches the filter.
   * @param {OfficialListFindUniqueArgs} args - Arguments to find a OfficialList
   * @example
   * // Get one OfficialList
   * const officialList = await prisma.officialList.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OfficialListFindUniqueArgs>(args: Prisma.SelectSubset<T, OfficialListFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OfficialList that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OfficialListFindUniqueOrThrowArgs} args - Arguments to find a OfficialList
   * @example
   * // Get one OfficialList
   * const officialList = await prisma.officialList.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OfficialListFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OfficialListFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfficialList that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialListFindFirstArgs} args - Arguments to find a OfficialList
   * @example
   * // Get one OfficialList
   * const officialList = await prisma.officialList.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OfficialListFindFirstArgs>(args?: Prisma.SelectSubset<T, OfficialListFindFirstArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfficialList that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialListFindFirstOrThrowArgs} args - Arguments to find a OfficialList
   * @example
   * // Get one OfficialList
   * const officialList = await prisma.officialList.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OfficialListFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OfficialListFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OfficialLists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialListFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OfficialLists
   * const officialLists = await prisma.officialList.findMany()
   *
   * // Get first 10 OfficialLists
   * const officialLists = await prisma.officialList.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const officialListWithIdOnly = await prisma.officialList.findMany({ select: { id: true } })
   *
   */
  findMany<T extends OfficialListFindManyArgs>(args?: Prisma.SelectSubset<T, OfficialListFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OfficialList.
   * @param {OfficialListCreateArgs} args - Arguments to create a OfficialList.
   * @example
   * // Create one OfficialList
   * const OfficialList = await prisma.officialList.create({
   *   data: {
   *     // ... data to create a OfficialList
   *   }
   * })
   *
   */
  create<T extends OfficialListCreateArgs>(args: Prisma.SelectSubset<T, OfficialListCreateArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OfficialLists.
   * @param {OfficialListCreateManyArgs} args - Arguments to create many OfficialLists.
   * @example
   * // Create many OfficialLists
   * const officialList = await prisma.officialList.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends OfficialListCreateManyArgs>(args?: Prisma.SelectSubset<T, OfficialListCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OfficialLists and returns the data saved in the database.
   * @param {OfficialListCreateManyAndReturnArgs} args - Arguments to create many OfficialLists.
   * @example
   * // Create many OfficialLists
   * const officialList = await prisma.officialList.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many OfficialLists and only return the `id`
   * const officialListWithIdOnly = await prisma.officialList.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends OfficialListCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OfficialListCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OfficialList.
   * @param {OfficialListDeleteArgs} args - Arguments to delete one OfficialList.
   * @example
   * // Delete one OfficialList
   * const OfficialList = await prisma.officialList.delete({
   *   where: {
   *     // ... filter to delete one OfficialList
   *   }
   * })
   *
   */
  delete<T extends OfficialListDeleteArgs>(args: Prisma.SelectSubset<T, OfficialListDeleteArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OfficialList.
   * @param {OfficialListUpdateArgs} args - Arguments to update one OfficialList.
   * @example
   * // Update one OfficialList
   * const officialList = await prisma.officialList.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends OfficialListUpdateArgs>(args: Prisma.SelectSubset<T, OfficialListUpdateArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OfficialLists.
   * @param {OfficialListDeleteManyArgs} args - Arguments to filter OfficialLists to delete.
   * @example
   * // Delete a few OfficialLists
   * const { count } = await prisma.officialList.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends OfficialListDeleteManyArgs>(args?: Prisma.SelectSubset<T, OfficialListDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfficialLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialListUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OfficialLists
   * const officialList = await prisma.officialList.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends OfficialListUpdateManyArgs>(args: Prisma.SelectSubset<T, OfficialListUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfficialLists and returns the data updated in the database.
   * @param {OfficialListUpdateManyAndReturnArgs} args - Arguments to update many OfficialLists.
   * @example
   * // Update many OfficialLists
   * const officialList = await prisma.officialList.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more OfficialLists and only return the `id`
   * const officialListWithIdOnly = await prisma.officialList.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends OfficialListUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OfficialListUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OfficialList.
   * @param {OfficialListUpsertArgs} args - Arguments to update or create a OfficialList.
   * @example
   * // Update or create a OfficialList
   * const officialList = await prisma.officialList.upsert({
   *   create: {
   *     // ... data to create a OfficialList
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OfficialList we want to update
   *   }
   * })
   */
  upsert<T extends OfficialListUpsertArgs>(args: Prisma.SelectSubset<T, OfficialListUpsertArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OfficialLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialListCountArgs} args - Arguments to filter OfficialLists to count.
   * @example
   * // Count the number of OfficialLists
   * const count = await prisma.officialList.count({
   *   where: {
   *     // ... the filter for the OfficialLists we want to count
   *   }
   * })
  **/
  count<T extends OfficialListCountArgs>(
    args?: Prisma.Subset<T, OfficialListCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OfficialListCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OfficialList.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialListAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OfficialListAggregateArgs>(args: Prisma.Subset<T, OfficialListAggregateArgs>): Prisma.PrismaPromise<GetOfficialListAggregateType<T>>

  /**
   * Group by OfficialList.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialListGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
  **/
  groupBy<
    T extends OfficialListGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OfficialListGroupByArgs['orderBy'] }
      : { orderBy?: OfficialListGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OfficialListGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOfficialListGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OfficialList model
 */
readonly fields: OfficialListFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OfficialList.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OfficialListClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  words<T extends Prisma.OfficialList$wordsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfficialList$wordsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  translationLanguages<T extends Prisma.OfficialList$translationLanguagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfficialList$translationLanguagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OfficialList model
 */
export interface OfficialListFieldRefs {
  readonly id: Prisma.FieldRef<"OfficialList", 'String'>
  readonly name: Prisma.FieldRef<"OfficialList", 'String'>
  readonly description: Prisma.FieldRef<"OfficialList", 'String'>
  readonly language: Prisma.FieldRef<"OfficialList", 'String'>
  readonly published: Prisma.FieldRef<"OfficialList", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"OfficialList", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OfficialList", 'DateTime'>
}


// Custom InputTypes
/**
 * OfficialList findUnique
 */
export type OfficialListFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialList to fetch.
   */
  where: Prisma.OfficialListWhereUniqueInput
}

/**
 * OfficialList findUniqueOrThrow
 */
export type OfficialListFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialList to fetch.
   */
  where: Prisma.OfficialListWhereUniqueInput
}

/**
 * OfficialList findFirst
 */
export type OfficialListFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialList to fetch.
   */
  where?: Prisma.OfficialListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialLists to fetch.
   */
  orderBy?: Prisma.OfficialListOrderByWithRelationInput | Prisma.OfficialListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OfficialLists.
   */
  cursor?: Prisma.OfficialListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialLists.
   */
  distinct?: Prisma.OfficialListScalarFieldEnum | Prisma.OfficialListScalarFieldEnum[]
}

/**
 * OfficialList findFirstOrThrow
 */
export type OfficialListFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialList to fetch.
   */
  where?: Prisma.OfficialListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialLists to fetch.
   */
  orderBy?: Prisma.OfficialListOrderByWithRelationInput | Prisma.OfficialListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OfficialLists.
   */
  cursor?: Prisma.OfficialListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialLists.
   */
  distinct?: Prisma.OfficialListScalarFieldEnum | Prisma.OfficialListScalarFieldEnum[]
}

/**
 * OfficialList findMany
 */
export type OfficialListFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialLists to fetch.
   */
  where?: Prisma.OfficialListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialLists to fetch.
   */
  orderBy?: Prisma.OfficialListOrderByWithRelationInput | Prisma.OfficialListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing OfficialLists.
   */
  cursor?: Prisma.OfficialListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialLists.
   */
  distinct?: Prisma.OfficialListScalarFieldEnum | Prisma.OfficialListScalarFieldEnum[]
}

/**
 * OfficialList create
 */
export type OfficialListCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * The data needed to create a OfficialList.
   */
  data: Prisma.XOR<Prisma.OfficialListCreateInput, Prisma.OfficialListUncheckedCreateInput>
}

/**
 * OfficialList createMany
 */
export type OfficialListCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OfficialLists.
   */
  data: Prisma.OfficialListCreateManyInput | Prisma.OfficialListCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OfficialList createManyAndReturn
 */
export type OfficialListCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * The data used to create many OfficialLists.
   */
  data: Prisma.OfficialListCreateManyInput | Prisma.OfficialListCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OfficialList update
 */
export type OfficialListUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * The data needed to update a OfficialList.
   */
  data: Prisma.XOR<Prisma.OfficialListUpdateInput, Prisma.OfficialListUncheckedUpdateInput>
  /**
   * Choose, which OfficialList to update.
   */
  where: Prisma.OfficialListWhereUniqueInput
}

/**
 * OfficialList updateMany
 */
export type OfficialListUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OfficialLists.
   */
  data: Prisma.XOR<Prisma.OfficialListUpdateManyMutationInput, Prisma.OfficialListUncheckedUpdateManyInput>
  /**
   * Filter which OfficialLists to update
   */
  where?: Prisma.OfficialListWhereInput
  /**
   * Limit how many OfficialLists to update.
   */
  limit?: number
}

/**
 * OfficialList updateManyAndReturn
 */
export type OfficialListUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * The data used to update OfficialLists.
   */
  data: Prisma.XOR<Prisma.OfficialListUpdateManyMutationInput, Prisma.OfficialListUncheckedUpdateManyInput>
  /**
   * Filter which OfficialLists to update
   */
  where?: Prisma.OfficialListWhereInput
  /**
   * Limit how many OfficialLists to update.
   */
  limit?: number
}

/**
 * OfficialList upsert
 */
export type OfficialListUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * The filter to search for the OfficialList to update in case it exists.
   */
  where: Prisma.OfficialListWhereUniqueInput
  /**
   * In case the OfficialList found by the `where` argument doesn't exist, create a new OfficialList with this data.
   */
  create: Prisma.XOR<Prisma.OfficialListCreateInput, Prisma.OfficialListUncheckedCreateInput>
  /**
   * In case the OfficialList was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OfficialListUpdateInput, Prisma.OfficialListUncheckedUpdateInput>
}

/**
 * OfficialList delete
 */
export type OfficialListDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
  /**
   * Filter which OfficialList to delete.
   */
  where: Prisma.OfficialListWhereUniqueInput
}

/**
 * OfficialList deleteMany
 */
export type OfficialListDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfficialLists to delete
   */
  where?: Prisma.OfficialListWhereInput
  /**
   * Limit how many OfficialLists to delete.
   */
  limit?: number
}

/**
 * OfficialList.words
 */
export type OfficialList$wordsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  where?: Prisma.OfficialWordWhereInput
  orderBy?: Prisma.OfficialWordOrderByWithRelationInput | Prisma.OfficialWordOrderByWithRelationInput[]
  cursor?: Prisma.OfficialWordWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OfficialWordScalarFieldEnum | Prisma.OfficialWordScalarFieldEnum[]
}

/**
 * OfficialList.translationLanguages
 */
export type OfficialList$translationLanguagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  where?: Prisma.OfficialTranslationListWhereInput
  orderBy?: Prisma.OfficialTranslationListOrderByWithRelationInput | Prisma.OfficialTranslationListOrderByWithRelationInput[]
  cursor?: Prisma.OfficialTranslationListWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OfficialTranslationListScalarFieldEnum | Prisma.OfficialTranslationListScalarFieldEnum[]
}

/**
 * OfficialList without action
 */
export type OfficialListDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialList
   */
  select?: Prisma.OfficialListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialList
   */
  omit?: Prisma.OfficialListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialListInclude<ExtArgs> | null
}
