
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `OfficialTranslationList` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OfficialTranslationList
 *
 */
export type OfficialTranslationListModel = runtime.Types.Result.DefaultSelection<Prisma.$OfficialTranslationListPayload>

export type AggregateOfficialTranslationList = {
  _count: OfficialTranslationListCountAggregateOutputType | null
  _min: OfficialTranslationListMinAggregateOutputType | null
  _max: OfficialTranslationListMaxAggregateOutputType | null
}

export type OfficialTranslationListMinAggregateOutputType = {
  id: string | null
  language: string | null
  note: string | null
  listId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OfficialTranslationListMaxAggregateOutputType = {
  id: string | null
  language: string | null
  note: string | null
  listId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OfficialTranslationListCountAggregateOutputType = {
  id: number
  language: number
  note: number
  listId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OfficialTranslationListMinAggregateInputType = {
  id?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
}

export type OfficialTranslationListMaxAggregateInputType = {
  id?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
}

export type OfficialTranslationListCountAggregateInputType = {
  id?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OfficialTranslationListAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfficialTranslationList to aggregate.
   */
  where?: Prisma.OfficialTranslationListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialTranslationLists to fetch.
   */
  orderBy?: Prisma.OfficialTranslationListOrderByWithRelationInput | Prisma.OfficialTranslationListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.OfficialTranslationListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialTranslationLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialTranslationLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned OfficialTranslationLists
  **/
  _count?: true | OfficialTranslationListCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
  **/
  _min?: OfficialTranslationListMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
  **/
  _max?: OfficialTranslationListMaxAggregateInputType
}

export type GetOfficialTranslationListAggregateType<T extends OfficialTranslationListAggregateArgs> = {
      [P in keyof T & keyof AggregateOfficialTranslationList]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOfficialTranslationList[P]>
    : Prisma.GetScalarType<T[P], AggregateOfficialTranslationList[P]>
}




export type OfficialTranslationListGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfficialTranslationListWhereInput
  orderBy?: Prisma.OfficialTranslationListOrderByWithAggregationInput | Prisma.OfficialTranslationListOrderByWithAggregationInput[]
  by: Prisma.OfficialTranslationListScalarFieldEnum[] | Prisma.OfficialTranslationListScalarFieldEnum
  having?: Prisma.OfficialTranslationListScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OfficialTranslationListCountAggregateInputType | true
  _min?: OfficialTranslationListMinAggregateInputType
  _max?: OfficialTranslationListMaxAggregateInputType
}

export type OfficialTranslationListGroupByOutputType = {
  id: string
  language: string
  note: string | null
  listId: string
  createdAt: Date
  updatedAt: Date
  _count: OfficialTranslationListCountAggregateOutputType | null
  _min: OfficialTranslationListMinAggregateOutputType | null
  _max: OfficialTranslationListMaxAggregateOutputType | null
}

export type GetOfficialTranslationListGroupByPayload<T extends OfficialTranslationListGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OfficialTranslationListGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OfficialTranslationListGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OfficialTranslationListGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OfficialTranslationListGroupByOutputType[P]>
      }
    >
  >



export type OfficialTranslationListWhereInput = {
  AND?: Prisma.OfficialTranslationListWhereInput | Prisma.OfficialTranslationListWhereInput[]
  OR?: Prisma.OfficialTranslationListWhereInput[]
  NOT?: Prisma.OfficialTranslationListWhereInput | Prisma.OfficialTranslationListWhereInput[]
  id?: Prisma.StringFilter<"OfficialTranslationList"> | string
  language?: Prisma.StringFilter<"OfficialTranslationList"> | string
  note?: Prisma.StringNullableFilter<"OfficialTranslationList"> | string | null
  listId?: Prisma.StringFilter<"OfficialTranslationList"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialTranslationList"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialTranslationList"> | Date | string
  list?: Prisma.XOR<Prisma.OfficialListScalarRelationFilter, Prisma.OfficialListWhereInput>
}

export type OfficialTranslationListOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  list?: Prisma.OfficialListOrderByWithRelationInput
}

export type OfficialTranslationListWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  listId_language?: Prisma.OfficialTranslationListListIdLanguageCompoundUniqueInput
  AND?: Prisma.OfficialTranslationListWhereInput | Prisma.OfficialTranslationListWhereInput[]
  OR?: Prisma.OfficialTranslationListWhereInput[]
  NOT?: Prisma.OfficialTranslationListWhereInput | Prisma.OfficialTranslationListWhereInput[]
  language?: Prisma.StringFilter<"OfficialTranslationList"> | string
  note?: Prisma.StringNullableFilter<"OfficialTranslationList"> | string | null
  listId?: Prisma.StringFilter<"OfficialTranslationList"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialTranslationList"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialTranslationList"> | Date | string
  list?: Prisma.XOR<Prisma.OfficialListScalarRelationFilter, Prisma.OfficialListWhereInput>
}, "id" | "listId_language">

export type OfficialTranslationListOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OfficialTranslationListCountOrderByAggregateInput
  _max?: Prisma.OfficialTranslationListMaxOrderByAggregateInput
  _min?: Prisma.OfficialTranslationListMinOrderByAggregateInput
}

export type OfficialTranslationListScalarWhereWithAggregatesInput = {
  AND?: Prisma.OfficialTranslationListScalarWhereWithAggregatesInput | Prisma.OfficialTranslationListScalarWhereWithAggregatesInput[]
  OR?: Prisma.OfficialTranslationListScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OfficialTranslationListScalarWhereWithAggregatesInput | Prisma.OfficialTranslationListScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OfficialTranslationList"> | string
  language?: Prisma.StringWithAggregatesFilter<"OfficialTranslationList"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"OfficialTranslationList"> | string | null
  listId?: Prisma.StringWithAggregatesFilter<"OfficialTranslationList"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OfficialTranslationList"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OfficialTranslationList"> | Date | string
}

export type OfficialTranslationListCreateInput = {
  id?: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.OfficialListCreateNestedOneWithoutTranslationLanguagesInput
}

export type OfficialTranslationListUncheckedCreateInput = {
  id?: string
  language: string
  note?: string | null
  listId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationListUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.OfficialListUpdateOneRequiredWithoutTranslationLanguagesNestedInput
}

export type OfficialTranslationListUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationListCreateManyInput = {
  id?: string
  language: string
  note?: string | null
  listId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationListUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationListUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationListListRelationFilter = {
  every?: Prisma.OfficialTranslationListWhereInput
  some?: Prisma.OfficialTranslationListWhereInput
  none?: Prisma.OfficialTranslationListWhereInput
}

export type OfficialTranslationListOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OfficialTranslationListListIdLanguageCompoundUniqueInput = {
  listId: string
  language: string
}

export type OfficialTranslationListCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialTranslationListMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialTranslationListMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialTranslationListCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.OfficialTranslationListCreateWithoutListInput, Prisma.OfficialTranslationListUncheckedCreateWithoutListInput> | Prisma.OfficialTranslationListCreateWithoutListInput[] | Prisma.OfficialTranslationListUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.OfficialTranslationListCreateOrConnectWithoutListInput | Prisma.OfficialTranslationListCreateOrConnectWithoutListInput[]
  createMany?: Prisma.OfficialTranslationListCreateManyListInputEnvelope
  connect?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
}

export type OfficialTranslationListUncheckedCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.OfficialTranslationListCreateWithoutListInput, Prisma.OfficialTranslationListUncheckedCreateWithoutListInput> | Prisma.OfficialTranslationListCreateWithoutListInput[] | Prisma.OfficialTranslationListUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.OfficialTranslationListCreateOrConnectWithoutListInput | Prisma.OfficialTranslationListCreateOrConnectWithoutListInput[]
  createMany?: Prisma.OfficialTranslationListCreateManyListInputEnvelope
  connect?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
}

export type OfficialTranslationListUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialTranslationListCreateWithoutListInput, Prisma.OfficialTranslationListUncheckedCreateWithoutListInput> | Prisma.OfficialTranslationListCreateWithoutListInput[] | Prisma.OfficialTranslationListUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.OfficialTranslationListCreateOrConnectWithoutListInput | Prisma.OfficialTranslationListCreateOrConnectWithoutListInput[]
  upsert?: Prisma.OfficialTranslationListUpsertWithWhereUniqueWithoutListInput | Prisma.OfficialTranslationListUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.OfficialTranslationListCreateManyListInputEnvelope
  set?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
  disconnect?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
  delete?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
  connect?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
  update?: Prisma.OfficialTranslationListUpdateWithWhereUniqueWithoutListInput | Prisma.OfficialTranslationListUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.OfficialTranslationListUpdateManyWithWhereWithoutListInput | Prisma.OfficialTranslationListUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.OfficialTranslationListScalarWhereInput | Prisma.OfficialTranslationListScalarWhereInput[]
}

export type OfficialTranslationListUncheckedUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialTranslationListCreateWithoutListInput, Prisma.OfficialTranslationListUncheckedCreateWithoutListInput> | Prisma.OfficialTranslationListCreateWithoutListInput[] | Prisma.OfficialTranslationListUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.OfficialTranslationListCreateOrConnectWithoutListInput | Prisma.OfficialTranslationListCreateOrConnectWithoutListInput[]
  upsert?: Prisma.OfficialTranslationListUpsertWithWhereUniqueWithoutListInput | Prisma.OfficialTranslationListUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.OfficialTranslationListCreateManyListInputEnvelope
  set?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
  disconnect?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
  delete?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
  connect?: Prisma.OfficialTranslationListWhereUniqueInput | Prisma.OfficialTranslationListWhereUniqueInput[]
  update?: Prisma.OfficialTranslationListUpdateWithWhereUniqueWithoutListInput | Prisma.OfficialTranslationListUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.OfficialTranslationListUpdateManyWithWhereWithoutListInput | Prisma.OfficialTranslationListUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.OfficialTranslationListScalarWhereInput | Prisma.OfficialTranslationListScalarWhereInput[]
}

export type OfficialTranslationListCreateWithoutListInput = {
  id?: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationListUncheckedCreateWithoutListInput = {
  id?: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationListCreateOrConnectWithoutListInput = {
  where: Prisma.OfficialTranslationListWhereUniqueInput
  create: Prisma.XOR<Prisma.OfficialTranslationListCreateWithoutListInput, Prisma.OfficialTranslationListUncheckedCreateWithoutListInput>
}

export type OfficialTranslationListCreateManyListInputEnvelope = {
  data: Prisma.OfficialTranslationListCreateManyListInput | Prisma.OfficialTranslationListCreateManyListInput[]
  skipDuplicates?: boolean
}

export type OfficialTranslationListUpsertWithWhereUniqueWithoutListInput = {
  where: Prisma.OfficialTranslationListWhereUniqueInput
  update: Prisma.XOR<Prisma.OfficialTranslationListUpdateWithoutListInput, Prisma.OfficialTranslationListUncheckedUpdateWithoutListInput>
  create: Prisma.XOR<Prisma.OfficialTranslationListCreateWithoutListInput, Prisma.OfficialTranslationListUncheckedCreateWithoutListInput>
}

export type OfficialTranslationListUpdateWithWhereUniqueWithoutListInput = {
  where: Prisma.OfficialTranslationListWhereUniqueInput
  data: Prisma.XOR<Prisma.OfficialTranslationListUpdateWithoutListInput, Prisma.OfficialTranslationListUncheckedUpdateWithoutListInput>
}

export type OfficialTranslationListUpdateManyWithWhereWithoutListInput = {
  where: Prisma.OfficialTranslationListScalarWhereInput
  data: Prisma.XOR<Prisma.OfficialTranslationListUpdateManyMutationInput, Prisma.OfficialTranslationListUncheckedUpdateManyWithoutListInput>
}

export type OfficialTranslationListScalarWhereInput = {
  AND?: Prisma.OfficialTranslationListScalarWhereInput | Prisma.OfficialTranslationListScalarWhereInput[]
  OR?: Prisma.OfficialTranslationListScalarWhereInput[]
  NOT?: Prisma.OfficialTranslationListScalarWhereInput | Prisma.OfficialTranslationListScalarWhereInput[]
  id?: Prisma.StringFilter<"OfficialTranslationList"> | string
  language?: Prisma.StringFilter<"OfficialTranslationList"> | string
  note?: Prisma.StringNullableFilter<"OfficialTranslationList"> | string | null
  listId?: Prisma.StringFilter<"OfficialTranslationList"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialTranslationList"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialTranslationList"> | Date | string
}

export type OfficialTranslationListCreateManyListInput = {
  id?: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialTranslationListUpdateWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationListUncheckedUpdateWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialTranslationListUncheckedUpdateManyWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type OfficialTranslationListSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialTranslationList"]>

export type OfficialTranslationListSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialTranslationList"]>

export type OfficialTranslationListSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialTranslationList"]>

export type OfficialTranslationListSelectScalar = {
  id?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OfficialTranslationListOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "language" | "note" | "listId" | "createdAt" | "updatedAt", ExtArgs["result"]["officialTranslationList"]>
export type OfficialTranslationListInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}
export type OfficialTranslationListIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}
export type OfficialTranslationListIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}

export type $OfficialTranslationListPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OfficialTranslationList"
  objects: {
    list: Prisma.$OfficialListPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    language: string
    note: string | null
    listId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["officialTranslationList"]>
  composites: {}
}

export type OfficialTranslationListGetPayload<S extends boolean | null | undefined | OfficialTranslationListDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload, S>

export type OfficialTranslationListCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OfficialTranslationListFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OfficialTranslationListCountAggregateInputType | true
  }

export interface OfficialTranslationListDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OfficialTranslationList'], meta: { name: 'OfficialTranslationList' } }
  /**
   * Find zero or one OfficialTranslationList that matches the filter.
   * @param {OfficialTranslationListFindUniqueArgs} args - Arguments to find a OfficialTranslationList
   * @example
   * // Get one OfficialTranslationList
   * const officialTranslationList = await prisma.officialTranslationList.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OfficialTranslationListFindUniqueArgs>(args: Prisma.SelectSubset<T, OfficialTranslationListFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationListClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OfficialTranslationList that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OfficialTranslationListFindUniqueOrThrowArgs} args - Arguments to find a OfficialTranslationList
   * @example
   * // Get one OfficialTranslationList
   * const officialTranslationList = await prisma.officialTranslationList.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OfficialTranslationListFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OfficialTranslationListFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationListClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfficialTranslationList that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationListFindFirstArgs} args - Arguments to find a OfficialTranslationList
   * @example
   * // Get one OfficialTranslationList
   * const officialTranslationList = await prisma.officialTranslationList.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OfficialTranslationListFindFirstArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationListFindFirstArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationListClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfficialTranslationList that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationListFindFirstOrThrowArgs} args - Arguments to find a OfficialTranslationList
   * @example
   * // Get one OfficialTranslationList
   * const officialTranslationList = await prisma.officialTranslationList.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OfficialTranslationListFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationListFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationListClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OfficialTranslationLists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationListFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OfficialTranslationLists
   * const officialTranslationLists = await prisma.officialTranslationList.findMany()
   *
   * // Get first 10 OfficialTranslationLists
   * const officialTranslationLists = await prisma.officialTranslationList.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const officialTranslationListWithIdOnly = await prisma.officialTranslationList.findMany({ select: { id: true } })
   *
   */
  findMany<T extends OfficialTranslationListFindManyArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationListFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OfficialTranslationList.
   * @param {OfficialTranslationListCreateArgs} args - Arguments to create a OfficialTranslationList.
   * @example
   * // Create one OfficialTranslationList
   * const OfficialTranslationList = await prisma.officialTranslationList.create({
   *   data: {
   *     // ... data to create a OfficialTranslationList
   *   }
   * })
   *
   */
  create<T extends OfficialTranslationListCreateArgs>(args: Prisma.SelectSubset<T, OfficialTranslationListCreateArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationListClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OfficialTranslationLists.
   * @param {OfficialTranslationListCreateManyArgs} args - Arguments to create many OfficialTranslationLists.
   * @example
   * // Create many OfficialTranslationLists
   * const officialTranslationList = await prisma.officialTranslationList.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends OfficialTranslationListCreateManyArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationListCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OfficialTranslationLists and returns the data saved in the database.
   * @param {OfficialTranslationListCreateManyAndReturnArgs} args - Arguments to create many OfficialTranslationLists.
   * @example
   * // Create many OfficialTranslationLists
   * const officialTranslationList = await prisma.officialTranslationList.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many OfficialTranslationLists and only return the `id`
   * const officialTranslationListWithIdOnly = await prisma.officialTranslationList.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends OfficialTranslationListCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationListCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OfficialTranslationList.
   * @param {OfficialTranslationListDeleteArgs} args - Arguments to delete one OfficialTranslationList.
   * @example
   * // Delete one OfficialTranslationList
   * const OfficialTranslationList = await prisma.officialTranslationList.delete({
   *   where: {
   *     // ... filter to delete one OfficialTranslationList
   *   }
   * })
   *
   */
  delete<T extends OfficialTranslationListDeleteArgs>(args: Prisma.SelectSubset<T, OfficialTranslationListDeleteArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationListClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OfficialTranslationList.
   * @param {OfficialTranslationListUpdateArgs} args - Arguments to update one OfficialTranslationList.
   * @example
   * // Update one OfficialTranslationList
   * const officialTranslationList = await prisma.officialTranslationList.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends OfficialTranslationListUpdateArgs>(args: Prisma.SelectSubset<T, OfficialTranslationListUpdateArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationListClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OfficialTranslationLists.
   * @param {OfficialTranslationListDeleteManyArgs} args - Arguments to filter OfficialTranslationLists to delete.
   * @example
   * // Delete a few OfficialTranslationLists
   * const { count } = await prisma.officialTranslationList.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends OfficialTranslationListDeleteManyArgs>(args?: Prisma.SelectSubset<T, OfficialTranslationListDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfficialTranslationLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationListUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OfficialTranslationLists
   * const officialTranslationList = await prisma.officialTranslationList.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends OfficialTranslationListUpdateManyArgs>(args: Prisma.SelectSubset<T, OfficialTranslationListUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfficialTranslationLists and returns the data updated in the database.
   * @param {OfficialTranslationListUpdateManyAndReturnArgs} args - Arguments to update many OfficialTranslationLists.
   * @example
   * // Update many OfficialTranslationLists
   * const officialTranslationList = await prisma.officialTranslationList.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more OfficialTranslationLists and only return the `id`
   * const officialTranslationListWithIdOnly = await prisma.officialTranslationList.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends OfficialTranslationListUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OfficialTranslationListUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OfficialTranslationList.
   * @param {OfficialTranslationListUpsertArgs} args - Arguments to update or create a OfficialTranslationList.
   * @example
   * // Update or create a OfficialTranslationList
   * const officialTranslationList = await prisma.officialTranslationList.upsert({
   *   create: {
   *     // ... data to create a OfficialTranslationList
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OfficialTranslationList we want to update
   *   }
   * })
   */
  upsert<T extends OfficialTranslationListUpsertArgs>(args: Prisma.SelectSubset<T, OfficialTranslationListUpsertArgs<ExtArgs>>): Prisma.Prisma__OfficialTranslationListClient<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationListPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OfficialTranslationLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationListCountArgs} args - Arguments to filter OfficialTranslationLists to count.
   * @example
   * // Count the number of OfficialTranslationLists
   * const count = await prisma.officialTranslationList.count({
   *   where: {
   *     // ... the filter for the OfficialTranslationLists we want to count
   *   }
   * })
  **/
  count<T extends OfficialTranslationListCountArgs>(
    args?: Prisma.Subset<T, OfficialTranslationListCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OfficialTranslationListCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OfficialTranslationList.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationListAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OfficialTranslationListAggregateArgs>(args: Prisma.Subset<T, OfficialTranslationListAggregateArgs>): Prisma.PrismaPromise<GetOfficialTranslationListAggregateType<T>>

  /**
   * Group by OfficialTranslationList.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialTranslationListGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
  **/
  groupBy<
    T extends OfficialTranslationListGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OfficialTranslationListGroupByArgs['orderBy'] }
      : { orderBy?: OfficialTranslationListGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OfficialTranslationListGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOfficialTranslationListGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OfficialTranslationList model
 */
readonly fields: OfficialTranslationListFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OfficialTranslationList.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OfficialTranslationListClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  list<T extends Prisma.OfficialListDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfficialListDefaultArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OfficialTranslationList model
 */
export interface OfficialTranslationListFieldRefs {
  readonly id: Prisma.FieldRef<"OfficialTranslationList", 'String'>
  readonly language: Prisma.FieldRef<"OfficialTranslationList", 'String'>
  readonly note: Prisma.FieldRef<"OfficialTranslationList", 'String'>
  readonly listId: Prisma.FieldRef<"OfficialTranslationList", 'String'>
  readonly createdAt: Prisma.FieldRef<"OfficialTranslationList", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OfficialTranslationList", 'DateTime'>
}


// Custom InputTypes
/**
 * OfficialTranslationList findUnique
 */
export type OfficialTranslationListFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationList to fetch.
   */
  where: Prisma.OfficialTranslationListWhereUniqueInput
}

/**
 * OfficialTranslationList findUniqueOrThrow
 */
export type OfficialTranslationListFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationList to fetch.
   */
  where: Prisma.OfficialTranslationListWhereUniqueInput
}

/**
 * OfficialTranslationList findFirst
 */
export type OfficialTranslationListFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationList to fetch.
   */
  where?: Prisma.OfficialTranslationListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialTranslationLists to fetch.
   */
  orderBy?: Prisma.OfficialTranslationListOrderByWithRelationInput | Prisma.OfficialTranslationListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OfficialTranslationLists.
   */
  cursor?: Prisma.OfficialTranslationListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialTranslationLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialTranslationLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialTranslationLists.
   */
  distinct?: Prisma.OfficialTranslationListScalarFieldEnum | Prisma.OfficialTranslationListScalarFieldEnum[]
}

/**
 * OfficialTranslationList findFirstOrThrow
 */
export type OfficialTranslationListFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationList to fetch.
   */
  where?: Prisma.OfficialTranslationListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialTranslationLists to fetch.
   */
  orderBy?: Prisma.OfficialTranslationListOrderByWithRelationInput | Prisma.OfficialTranslationListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OfficialTranslationLists.
   */
  cursor?: Prisma.OfficialTranslationListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialTranslationLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialTranslationLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialTranslationLists.
   */
  distinct?: Prisma.OfficialTranslationListScalarFieldEnum | Prisma.OfficialTranslationListScalarFieldEnum[]
}

/**
 * OfficialTranslationList findMany
 */
export type OfficialTranslationListFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * Filter, which OfficialTranslationLists to fetch.
   */
  where?: Prisma.OfficialTranslationListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialTranslationLists to fetch.
   */
  orderBy?: Prisma.OfficialTranslationListOrderByWithRelationInput | Prisma.OfficialTranslationListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing OfficialTranslationLists.
   */
  cursor?: Prisma.OfficialTranslationListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialTranslationLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialTranslationLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialTranslationLists.
   */
  distinct?: Prisma.OfficialTranslationListScalarFieldEnum | Prisma.OfficialTranslationListScalarFieldEnum[]
}

/**
 * OfficialTranslationList create
 */
export type OfficialTranslationListCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * The data needed to create a OfficialTranslationList.
   */
  data: Prisma.XOR<Prisma.OfficialTranslationListCreateInput, Prisma.OfficialTranslationListUncheckedCreateInput>
}

/**
 * OfficialTranslationList createMany
 */
export type OfficialTranslationListCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OfficialTranslationLists.
   */
  data: Prisma.OfficialTranslationListCreateManyInput | Prisma.OfficialTranslationListCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OfficialTranslationList createManyAndReturn
 */
export type OfficialTranslationListCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * The data used to create many OfficialTranslationLists.
   */
  data: Prisma.OfficialTranslationListCreateManyInput | Prisma.OfficialTranslationListCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OfficialTranslationList update
 */
export type OfficialTranslationListUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * The data needed to update a OfficialTranslationList.
   */
  data: Prisma.XOR<Prisma.OfficialTranslationListUpdateInput, Prisma.OfficialTranslationListUncheckedUpdateInput>
  /**
   * Choose, which OfficialTranslationList to update.
   */
  where: Prisma.OfficialTranslationListWhereUniqueInput
}

/**
 * OfficialTranslationList updateMany
 */
export type OfficialTranslationListUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OfficialTranslationLists.
   */
  data: Prisma.XOR<Prisma.OfficialTranslationListUpdateManyMutationInput, Prisma.OfficialTranslationListUncheckedUpdateManyInput>
  /**
   * Filter which OfficialTranslationLists to update
   */
  where?: Prisma.OfficialTranslationListWhereInput
  /**
   * Limit how many OfficialTranslationLists to update.
   */
  limit?: number
}

/**
 * OfficialTranslationList updateManyAndReturn
 */
export type OfficialTranslationListUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * The data used to update OfficialTranslationLists.
   */
  data: Prisma.XOR<Prisma.OfficialTranslationListUpdateManyMutationInput, Prisma.OfficialTranslationListUncheckedUpdateManyInput>
  /**
   * Filter which OfficialTranslationLists to update
   */
  where?: Prisma.OfficialTranslationListWhereInput
  /**
   * Limit how many OfficialTranslationLists to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OfficialTranslationList upsert
 */
export type OfficialTranslationListUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * The filter to search for the OfficialTranslationList to update in case it exists.
   */
  where: Prisma.OfficialTranslationListWhereUniqueInput
  /**
   * In case the OfficialTranslationList found by the `where` argument doesn't exist, create a new OfficialTranslationList with this data.
   */
  create: Prisma.XOR<Prisma.OfficialTranslationListCreateInput, Prisma.OfficialTranslationListUncheckedCreateInput>
  /**
   * In case the OfficialTranslationList was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OfficialTranslationListUpdateInput, Prisma.OfficialTranslationListUncheckedUpdateInput>
}

/**
 * OfficialTranslationList delete
 */
export type OfficialTranslationListDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
  /**
   * Filter which OfficialTranslationList to delete.
   */
  where: Prisma.OfficialTranslationListWhereUniqueInput
}

/**
 * OfficialTranslationList deleteMany
 */
export type OfficialTranslationListDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfficialTranslationLists to delete
   */
  where?: Prisma.OfficialTranslationListWhereInput
  /**
   * Limit how many OfficialTranslationLists to delete.
   */
  limit?: number
}

/**
 * OfficialTranslationList without action
 */
export type OfficialTranslationListDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationList
   */
  select?: Prisma.OfficialTranslationListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationList
   */
  omit?: Prisma.OfficialTranslationListOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationListInclude<ExtArgs> | null
}
