
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `OfficialWord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OfficialWord
 *
 */
export type OfficialWordModel = runtime.Types.Result.DefaultSelection<Prisma.$OfficialWordPayload>

export type AggregateOfficialWord = {
  _count: OfficialWordCountAggregateOutputType | null
  _min: OfficialWordMinAggregateOutputType | null
  _max: OfficialWordMaxAggregateOutputType | null
}

export type OfficialWordMinAggregateOutputType = {
  id: string | null
  text: string | null
  language: string | null
  note: string | null
  listId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OfficialWordMaxAggregateOutputType = {
  id: string | null
  text: string | null
  language: string | null
  note: string | null
  listId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OfficialWordCountAggregateOutputType = {
  id: number
  text: number
  language: number
  note: number
  listId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OfficialWordMinAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
}

export type OfficialWordMaxAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
}

export type OfficialWordCountAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OfficialWordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfficialWord to aggregate.
   */
  where?: Prisma.OfficialWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialWords to fetch.
   */
  orderBy?: Prisma.OfficialWordOrderByWithRelationInput | Prisma.OfficialWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.OfficialWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned OfficialWords
  **/
  _count?: true | OfficialWordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
  **/
  _min?: OfficialWordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
  **/
  _max?: OfficialWordMaxAggregateInputType
}

export type GetOfficialWordAggregateType<T extends OfficialWordAggregateArgs> = {
      [P in keyof T & keyof AggregateOfficialWord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOfficialWord[P]>
    : Prisma.GetScalarType<T[P], AggregateOfficialWord[P]>
}




export type OfficialWordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfficialWordWhereInput
  orderBy?: Prisma.OfficialWordOrderByWithAggregationInput | Prisma.OfficialWordOrderByWithAggregationInput[]
  by: Prisma.OfficialWordScalarFieldEnum[] | Prisma.OfficialWordScalarFieldEnum
  having?: Prisma.OfficialWordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OfficialWordCountAggregateInputType | true
  _min?: OfficialWordMinAggregateInputType
  _max?: OfficialWordMaxAggregateInputType
}

export type OfficialWordGroupByOutputType = {
  id: string
  text: string
  language: string
  note: string | null
  listId: string
  createdAt: Date
  updatedAt: Date
  _count: OfficialWordCountAggregateOutputType | null
  _min: OfficialWordMinAggregateOutputType | null
  _max: OfficialWordMaxAggregateOutputType | null
}

export type GetOfficialWordGroupByPayload<T extends OfficialWordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OfficialWordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OfficialWordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OfficialWordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OfficialWordGroupByOutputType[P]>
      }
    >
  >



export type OfficialWordWhereInput = {
  AND?: Prisma.OfficialWordWhereInput | Prisma.OfficialWordWhereInput[]
  OR?: Prisma.OfficialWordWhereInput[]
  NOT?: Prisma.OfficialWordWhereInput | Prisma.OfficialWordWhereInput[]
  id?: Prisma.StringFilter<"OfficialWord"> | string
  text?: Prisma.StringFilter<"OfficialWord"> | string
  language?: Prisma.StringFilter<"OfficialWord"> | string
  note?: Prisma.StringNullableFilter<"OfficialWord"> | string | null
  listId?: Prisma.StringFilter<"OfficialWord"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialWord"> | Date | string
  list?: Prisma.XOR<Prisma.OfficialListScalarRelationFilter, Prisma.OfficialListWhereInput>
  translations?: Prisma.OfficialTranslationWordListRelationFilter
}

export type OfficialWordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  list?: Prisma.OfficialListOrderByWithRelationInput
  translations?: Prisma.OfficialTranslationWordOrderByRelationAggregateInput
}

export type OfficialWordWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.OfficialWordWhereInput | Prisma.OfficialWordWhereInput[]
  OR?: Prisma.OfficialWordWhereInput[]
  NOT?: Prisma.OfficialWordWhereInput | Prisma.OfficialWordWhereInput[]
  text?: Prisma.StringFilter<"OfficialWord"> | string
  language?: Prisma.StringFilter<"OfficialWord"> | string
  note?: Prisma.StringNullableFilter<"OfficialWord"> | string | null
  listId?: Prisma.StringFilter<"OfficialWord"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialWord"> | Date | string
  list?: Prisma.XOR<Prisma.OfficialListScalarRelationFilter, Prisma.OfficialListWhereInput>
  translations?: Prisma.OfficialTranslationWordListRelationFilter
}, "id">

export type OfficialWordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OfficialWordCountOrderByAggregateInput
  _max?: Prisma.OfficialWordMaxOrderByAggregateInput
  _min?: Prisma.OfficialWordMinOrderByAggregateInput
}

export type OfficialWordScalarWhereWithAggregatesInput = {
  AND?: Prisma.OfficialWordScalarWhereWithAggregatesInput | Prisma.OfficialWordScalarWhereWithAggregatesInput[]
  OR?: Prisma.OfficialWordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OfficialWordScalarWhereWithAggregatesInput | Prisma.OfficialWordScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OfficialWord"> | string
  text?: Prisma.StringWithAggregatesFilter<"OfficialWord"> | string
  language?: Prisma.StringWithAggregatesFilter<"OfficialWord"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"OfficialWord"> | string | null
  listId?: Prisma.StringWithAggregatesFilter<"OfficialWord"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OfficialWord"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OfficialWord"> | Date | string
}

export type OfficialWordCreateInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.OfficialListCreateNestedOneWithoutWordsInput
  translations?: Prisma.OfficialTranslationWordCreateNestedManyWithoutWordInput
}

export type OfficialWordUncheckedCreateInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  listId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  translations?: Prisma.OfficialTranslationWordUncheckedCreateNestedManyWithoutWordInput
}

export type OfficialWordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.OfficialListUpdateOneRequiredWithoutWordsNestedInput
  translations?: Prisma.OfficialTranslationWordUpdateManyWithoutWordNestedInput
}

export type OfficialWordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  translations?: Prisma.OfficialTranslationWordUncheckedUpdateManyWithoutWordNestedInput
}

export type OfficialWordCreateManyInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  listId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialWordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialWordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialWordListRelationFilter = {
  every?: Prisma.OfficialWordWhereInput
  some?: Prisma.OfficialWordWhereInput
  none?: Prisma.OfficialWordWhereInput
}

export type OfficialWordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OfficialWordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialWordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialWordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OfficialWordScalarRelationFilter = {
  is?: Prisma.OfficialWordWhereInput
  isNot?: Prisma.OfficialWordWhereInput
}

export type OfficialWordCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.OfficialWordCreateWithoutListInput, Prisma.OfficialWordUncheckedCreateWithoutListInput> | Prisma.OfficialWordCreateWithoutListInput[] | Prisma.OfficialWordUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.OfficialWordCreateOrConnectWithoutListInput | Prisma.OfficialWordCreateOrConnectWithoutListInput[]
  createMany?: Prisma.OfficialWordCreateManyListInputEnvelope
  connect?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
}

export type OfficialWordUncheckedCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.OfficialWordCreateWithoutListInput, Prisma.OfficialWordUncheckedCreateWithoutListInput> | Prisma.OfficialWordCreateWithoutListInput[] | Prisma.OfficialWordUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.OfficialWordCreateOrConnectWithoutListInput | Prisma.OfficialWordCreateOrConnectWithoutListInput[]
  createMany?: Prisma.OfficialWordCreateManyListInputEnvelope
  connect?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
}

export type OfficialWordUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialWordCreateWithoutListInput, Prisma.OfficialWordUncheckedCreateWithoutListInput> | Prisma.OfficialWordCreateWithoutListInput[] | Prisma.OfficialWordUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.OfficialWordCreateOrConnectWithoutListInput | Prisma.OfficialWordCreateOrConnectWithoutListInput[]
  upsert?: Prisma.OfficialWordUpsertWithWhereUniqueWithoutListInput | Prisma.OfficialWordUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.OfficialWordCreateManyListInputEnvelope
  set?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
  disconnect?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
  delete?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
  connect?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
  update?: Prisma.OfficialWordUpdateWithWhereUniqueWithoutListInput | Prisma.OfficialWordUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.OfficialWordUpdateManyWithWhereWithoutListInput | Prisma.OfficialWordUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.OfficialWordScalarWhereInput | Prisma.OfficialWordScalarWhereInput[]
}

export type OfficialWordUncheckedUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialWordCreateWithoutListInput, Prisma.OfficialWordUncheckedCreateWithoutListInput> | Prisma.OfficialWordCreateWithoutListInput[] | Prisma.OfficialWordUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.OfficialWordCreateOrConnectWithoutListInput | Prisma.OfficialWordCreateOrConnectWithoutListInput[]
  upsert?: Prisma.OfficialWordUpsertWithWhereUniqueWithoutListInput | Prisma.OfficialWordUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.OfficialWordCreateManyListInputEnvelope
  set?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
  disconnect?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
  delete?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
  connect?: Prisma.OfficialWordWhereUniqueInput | Prisma.OfficialWordWhereUniqueInput[]
  update?: Prisma.OfficialWordUpdateWithWhereUniqueWithoutListInput | Prisma.OfficialWordUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.OfficialWordUpdateManyWithWhereWithoutListInput | Prisma.OfficialWordUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.OfficialWordScalarWhereInput | Prisma.OfficialWordScalarWhereInput[]
}

export type OfficialWordCreateNestedOneWithoutTranslationsInput = {
  create?: Prisma.XOR<Prisma.OfficialWordCreateWithoutTranslationsInput, Prisma.OfficialWordUncheckedCreateWithoutTranslationsInput>
  connectOrCreate?: Prisma.OfficialWordCreateOrConnectWithoutTranslationsInput
  connect?: Prisma.OfficialWordWhereUniqueInput
}

export type OfficialWordUpdateOneRequiredWithoutTranslationsNestedInput = {
  create?: Prisma.XOR<Prisma.OfficialWordCreateWithoutTranslationsInput, Prisma.OfficialWordUncheckedCreateWithoutTranslationsInput>
  connectOrCreate?: Prisma.OfficialWordCreateOrConnectWithoutTranslationsInput
  upsert?: Prisma.OfficialWordUpsertWithoutTranslationsInput
  connect?: Prisma.OfficialWordWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OfficialWordUpdateToOneWithWhereWithoutTranslationsInput, Prisma.OfficialWordUpdateWithoutTranslationsInput>, Prisma.OfficialWordUncheckedUpdateWithoutTranslationsInput>
}

export type OfficialWordCreateWithoutListInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  translations?: Prisma.OfficialTranslationWordCreateNestedManyWithoutWordInput
}

export type OfficialWordUncheckedCreateWithoutListInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  translations?: Prisma.OfficialTranslationWordUncheckedCreateNestedManyWithoutWordInput
}

export type OfficialWordCreateOrConnectWithoutListInput = {
  where: Prisma.OfficialWordWhereUniqueInput
  create: Prisma.XOR<Prisma.OfficialWordCreateWithoutListInput, Prisma.OfficialWordUncheckedCreateWithoutListInput>
}

export type OfficialWordCreateManyListInputEnvelope = {
  data: Prisma.OfficialWordCreateManyListInput | Prisma.OfficialWordCreateManyListInput[]
  skipDuplicates?: boolean
}

export type OfficialWordUpsertWithWhereUniqueWithoutListInput = {
  where: Prisma.OfficialWordWhereUniqueInput
  update: Prisma.XOR<Prisma.OfficialWordUpdateWithoutListInput, Prisma.OfficialWordUncheckedUpdateWithoutListInput>
  create: Prisma.XOR<Prisma.OfficialWordCreateWithoutListInput, Prisma.OfficialWordUncheckedCreateWithoutListInput>
}

export type OfficialWordUpdateWithWhereUniqueWithoutListInput = {
  where: Prisma.OfficialWordWhereUniqueInput
  data: Prisma.XOR<Prisma.OfficialWordUpdateWithoutListInput, Prisma.OfficialWordUncheckedUpdateWithoutListInput>
}

export type OfficialWordUpdateManyWithWhereWithoutListInput = {
  where: Prisma.OfficialWordScalarWhereInput
  data: Prisma.XOR<Prisma.OfficialWordUpdateManyMutationInput, Prisma.OfficialWordUncheckedUpdateManyWithoutListInput>
}

export type OfficialWordScalarWhereInput = {
  AND?: Prisma.OfficialWordScalarWhereInput | Prisma.OfficialWordScalarWhereInput[]
  OR?: Prisma.OfficialWordScalarWhereInput[]
  NOT?: Prisma.OfficialWordScalarWhereInput | Prisma.OfficialWordScalarWhereInput[]
  id?: Prisma.StringFilter<"OfficialWord"> | string
  text?: Prisma.StringFilter<"OfficialWord"> | string
  language?: Prisma.StringFilter<"OfficialWord"> | string
  note?: Prisma.StringNullableFilter<"OfficialWord"> | string | null
  listId?: Prisma.StringFilter<"OfficialWord"> | string
  createdAt?: Prisma.DateTimeFilter<"OfficialWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OfficialWord"> | Date | string
}

export type OfficialWordCreateWithoutTranslationsInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.OfficialListCreateNestedOneWithoutWordsInput
}

export type OfficialWordUncheckedCreateWithoutTranslationsInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  listId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialWordCreateOrConnectWithoutTranslationsInput = {
  where: Prisma.OfficialWordWhereUniqueInput
  create: Prisma.XOR<Prisma.OfficialWordCreateWithoutTranslationsInput, Prisma.OfficialWordUncheckedCreateWithoutTranslationsInput>
}

export type OfficialWordUpsertWithoutTranslationsInput = {
  update: Prisma.XOR<Prisma.OfficialWordUpdateWithoutTranslationsInput, Prisma.OfficialWordUncheckedUpdateWithoutTranslationsInput>
  create: Prisma.XOR<Prisma.OfficialWordCreateWithoutTranslationsInput, Prisma.OfficialWordUncheckedCreateWithoutTranslationsInput>
  where?: Prisma.OfficialWordWhereInput
}

export type OfficialWordUpdateToOneWithWhereWithoutTranslationsInput = {
  where?: Prisma.OfficialWordWhereInput
  data: Prisma.XOR<Prisma.OfficialWordUpdateWithoutTranslationsInput, Prisma.OfficialWordUncheckedUpdateWithoutTranslationsInput>
}

export type OfficialWordUpdateWithoutTranslationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.OfficialListUpdateOneRequiredWithoutWordsNestedInput
}

export type OfficialWordUncheckedUpdateWithoutTranslationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OfficialWordCreateManyListInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OfficialWordUpdateWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  translations?: Prisma.OfficialTranslationWordUpdateManyWithoutWordNestedInput
}

export type OfficialWordUncheckedUpdateWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  translations?: Prisma.OfficialTranslationWordUncheckedUpdateManyWithoutWordNestedInput
}

export type OfficialWordUncheckedUpdateManyWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type OfficialWordCountOutputType
 */

export type OfficialWordCountOutputType = {
  translations: number
}

export type OfficialWordCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  translations?: boolean | OfficialWordCountOutputTypeCountTranslationsArgs
}

/**
 * OfficialWordCountOutputType without action
 */
export type OfficialWordCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWordCountOutputType
   */
  select?: Prisma.OfficialWordCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OfficialWordCountOutputType without action
 */
export type OfficialWordCountOutputTypeCountTranslationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OfficialTranslationWordWhereInput
}


export type OfficialWordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
  translations?: boolean | Prisma.OfficialWord$translationsArgs<ExtArgs>
  _count?: boolean | Prisma.OfficialWordCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialWord"]>

export type OfficialWordSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialWord"]>

export type OfficialWordSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["officialWord"]>

export type OfficialWordSelectScalar = {
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OfficialWordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "text" | "language" | "note" | "listId" | "createdAt" | "updatedAt", ExtArgs["result"]["officialWord"]>
export type OfficialWordInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
  translations?: boolean | Prisma.OfficialWord$translationsArgs<ExtArgs>
  _count?: boolean | Prisma.OfficialWordCountOutputTypeDefaultArgs<ExtArgs>
}
export type OfficialWordIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}
export type OfficialWordIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.OfficialListDefaultArgs<ExtArgs>
}

export type $OfficialWordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OfficialWord"
  objects: {
    list: Prisma.$OfficialListPayload<ExtArgs>
    translations: Prisma.$OfficialTranslationWordPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    text: string
    language: string
    note: string | null
    listId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["officialWord"]>
  composites: {}
}

export type OfficialWordGetPayload<S extends boolean | null | undefined | OfficialWordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload, S>

export type OfficialWordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OfficialWordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OfficialWordCountAggregateInputType | true
  }

export interface OfficialWordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OfficialWord'], meta: { name: 'OfficialWord' } }
  /**
   * Find zero or one OfficialWord that matches the filter.
   * @param {OfficialWordFindUniqueArgs} args - Arguments to find a OfficialWord
   * @example
   * // Get one OfficialWord
   * const officialWord = await prisma.officialWord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OfficialWordFindUniqueArgs>(args: Prisma.SelectSubset<T, OfficialWordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OfficialWord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OfficialWordFindUniqueOrThrowArgs} args - Arguments to find a OfficialWord
   * @example
   * // Get one OfficialWord
   * const officialWord = await prisma.officialWord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OfficialWordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OfficialWordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfficialWord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialWordFindFirstArgs} args - Arguments to find a OfficialWord
   * @example
   * // Get one OfficialWord
   * const officialWord = await prisma.officialWord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OfficialWordFindFirstArgs>(args?: Prisma.SelectSubset<T, OfficialWordFindFirstArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OfficialWord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialWordFindFirstOrThrowArgs} args - Arguments to find a OfficialWord
   * @example
   * // Get one OfficialWord
   * const officialWord = await prisma.officialWord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OfficialWordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OfficialWordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OfficialWords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialWordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OfficialWords
   * const officialWords = await prisma.officialWord.findMany()
   *
   * // Get first 10 OfficialWords
   * const officialWords = await prisma.officialWord.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const officialWordWithIdOnly = await prisma.officialWord.findMany({ select: { id: true } })
   *
   */
  findMany<T extends OfficialWordFindManyArgs>(args?: Prisma.SelectSubset<T, OfficialWordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OfficialWord.
   * @param {OfficialWordCreateArgs} args - Arguments to create a OfficialWord.
   * @example
   * // Create one OfficialWord
   * const OfficialWord = await prisma.officialWord.create({
   *   data: {
   *     // ... data to create a OfficialWord
   *   }
   * })
   *
   */
  create<T extends OfficialWordCreateArgs>(args: Prisma.SelectSubset<T, OfficialWordCreateArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OfficialWords.
   * @param {OfficialWordCreateManyArgs} args - Arguments to create many OfficialWords.
   * @example
   * // Create many OfficialWords
   * const officialWord = await prisma.officialWord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends OfficialWordCreateManyArgs>(args?: Prisma.SelectSubset<T, OfficialWordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OfficialWords and returns the data saved in the database.
   * @param {OfficialWordCreateManyAndReturnArgs} args - Arguments to create many OfficialWords.
   * @example
   * // Create many OfficialWords
   * const officialWord = await prisma.officialWord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many OfficialWords and only return the `id`
   * const officialWordWithIdOnly = await prisma.officialWord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends OfficialWordCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OfficialWordCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OfficialWord.
   * @param {OfficialWordDeleteArgs} args - Arguments to delete one OfficialWord.
   * @example
   * // Delete one OfficialWord
   * const OfficialWord = await prisma.officialWord.delete({
   *   where: {
   *     // ... filter to delete one OfficialWord
   *   }
   * })
   *
   */
  delete<T extends OfficialWordDeleteArgs>(args: Prisma.SelectSubset<T, OfficialWordDeleteArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OfficialWord.
   * @param {OfficialWordUpdateArgs} args - Arguments to update one OfficialWord.
   * @example
   * // Update one OfficialWord
   * const officialWord = await prisma.officialWord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends OfficialWordUpdateArgs>(args: Prisma.SelectSubset<T, OfficialWordUpdateArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OfficialWords.
   * @param {OfficialWordDeleteManyArgs} args - Arguments to filter OfficialWords to delete.
   * @example
   * // Delete a few OfficialWords
   * const { count } = await prisma.officialWord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends OfficialWordDeleteManyArgs>(args?: Prisma.SelectSubset<T, OfficialWordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfficialWords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialWordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OfficialWords
   * const officialWord = await prisma.officialWord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends OfficialWordUpdateManyArgs>(args: Prisma.SelectSubset<T, OfficialWordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OfficialWords and returns the data updated in the database.
   * @param {OfficialWordUpdateManyAndReturnArgs} args - Arguments to update many OfficialWords.
   * @example
   * // Update many OfficialWords
   * const officialWord = await prisma.officialWord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more OfficialWords and only return the `id`
   * const officialWordWithIdOnly = await prisma.officialWord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends OfficialWordUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OfficialWordUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OfficialWord.
   * @param {OfficialWordUpsertArgs} args - Arguments to update or create a OfficialWord.
   * @example
   * // Update or create a OfficialWord
   * const officialWord = await prisma.officialWord.upsert({
   *   create: {
   *     // ... data to create a OfficialWord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OfficialWord we want to update
   *   }
   * })
   */
  upsert<T extends OfficialWordUpsertArgs>(args: Prisma.SelectSubset<T, OfficialWordUpsertArgs<ExtArgs>>): Prisma.Prisma__OfficialWordClient<runtime.Types.Result.GetResult<Prisma.$OfficialWordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OfficialWords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialWordCountArgs} args - Arguments to filter OfficialWords to count.
   * @example
   * // Count the number of OfficialWords
   * const count = await prisma.officialWord.count({
   *   where: {
   *     // ... the filter for the OfficialWords we want to count
   *   }
   * })
  **/
  count<T extends OfficialWordCountArgs>(
    args?: Prisma.Subset<T, OfficialWordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OfficialWordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OfficialWord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialWordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OfficialWordAggregateArgs>(args: Prisma.Subset<T, OfficialWordAggregateArgs>): Prisma.PrismaPromise<GetOfficialWordAggregateType<T>>

  /**
   * Group by OfficialWord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OfficialWordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
  **/
  groupBy<
    T extends OfficialWordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OfficialWordGroupByArgs['orderBy'] }
      : { orderBy?: OfficialWordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OfficialWordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOfficialWordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OfficialWord model
 */
readonly fields: OfficialWordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OfficialWord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OfficialWordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  list<T extends Prisma.OfficialListDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfficialListDefaultArgs<ExtArgs>>): Prisma.Prisma__OfficialListClient<runtime.Types.Result.GetResult<Prisma.$OfficialListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  translations<T extends Prisma.OfficialWord$translationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OfficialWord$translationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OfficialTranslationWordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OfficialWord model
 */
export interface OfficialWordFieldRefs {
  readonly id: Prisma.FieldRef<"OfficialWord", 'String'>
  readonly text: Prisma.FieldRef<"OfficialWord", 'String'>
  readonly language: Prisma.FieldRef<"OfficialWord", 'String'>
  readonly note: Prisma.FieldRef<"OfficialWord", 'String'>
  readonly listId: Prisma.FieldRef<"OfficialWord", 'String'>
  readonly createdAt: Prisma.FieldRef<"OfficialWord", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OfficialWord", 'DateTime'>
}


// Custom InputTypes
/**
 * OfficialWord findUnique
 */
export type OfficialWordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialWord to fetch.
   */
  where: Prisma.OfficialWordWhereUniqueInput
}

/**
 * OfficialWord findUniqueOrThrow
 */
export type OfficialWordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialWord to fetch.
   */
  where: Prisma.OfficialWordWhereUniqueInput
}

/**
 * OfficialWord findFirst
 */
export type OfficialWordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialWord to fetch.
   */
  where?: Prisma.OfficialWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialWords to fetch.
   */
  orderBy?: Prisma.OfficialWordOrderByWithRelationInput | Prisma.OfficialWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OfficialWords.
   */
  cursor?: Prisma.OfficialWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialWords.
   */
  distinct?: Prisma.OfficialWordScalarFieldEnum | Prisma.OfficialWordScalarFieldEnum[]
}

/**
 * OfficialWord findFirstOrThrow
 */
export type OfficialWordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialWord to fetch.
   */
  where?: Prisma.OfficialWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialWords to fetch.
   */
  orderBy?: Prisma.OfficialWordOrderByWithRelationInput | Prisma.OfficialWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for OfficialWords.
   */
  cursor?: Prisma.OfficialWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialWords.
   */
  distinct?: Prisma.OfficialWordScalarFieldEnum | Prisma.OfficialWordScalarFieldEnum[]
}

/**
 * OfficialWord findMany
 */
export type OfficialWordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * Filter, which OfficialWords to fetch.
   */
  where?: Prisma.OfficialWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of OfficialWords to fetch.
   */
  orderBy?: Prisma.OfficialWordOrderByWithRelationInput | Prisma.OfficialWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing OfficialWords.
   */
  cursor?: Prisma.OfficialWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` OfficialWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` OfficialWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of OfficialWords.
   */
  distinct?: Prisma.OfficialWordScalarFieldEnum | Prisma.OfficialWordScalarFieldEnum[]
}

/**
 * OfficialWord create
 */
export type OfficialWordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * The data needed to create a OfficialWord.
   */
  data: Prisma.XOR<Prisma.OfficialWordCreateInput, Prisma.OfficialWordUncheckedCreateInput>
}

/**
 * OfficialWord createMany
 */
export type OfficialWordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OfficialWords.
   */
  data: Prisma.OfficialWordCreateManyInput | Prisma.OfficialWordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OfficialWord createManyAndReturn
 */
export type OfficialWordCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * The data used to create many OfficialWords.
   */
  data: Prisma.OfficialWordCreateManyInput | Prisma.OfficialWordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OfficialWord update
 */
export type OfficialWordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * The data needed to update a OfficialWord.
   */
  data: Prisma.XOR<Prisma.OfficialWordUpdateInput, Prisma.OfficialWordUncheckedUpdateInput>
  /**
   * Choose, which OfficialWord to update.
   */
  where: Prisma.OfficialWordWhereUniqueInput
}

/**
 * OfficialWord updateMany
 */
export type OfficialWordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OfficialWords.
   */
  data: Prisma.XOR<Prisma.OfficialWordUpdateManyMutationInput, Prisma.OfficialWordUncheckedUpdateManyInput>
  /**
   * Filter which OfficialWords to update
   */
  where?: Prisma.OfficialWordWhereInput
  /**
   * Limit how many OfficialWords to update.
   */
  limit?: number
}

/**
 * OfficialWord updateManyAndReturn
 */
export type OfficialWordUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * The data used to update OfficialWords.
   */
  data: Prisma.XOR<Prisma.OfficialWordUpdateManyMutationInput, Prisma.OfficialWordUncheckedUpdateManyInput>
  /**
   * Filter which OfficialWords to update
   */
  where?: Prisma.OfficialWordWhereInput
  /**
   * Limit how many OfficialWords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OfficialWord upsert
 */
export type OfficialWordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * The filter to search for the OfficialWord to update in case it exists.
   */
  where: Prisma.OfficialWordWhereUniqueInput
  /**
   * In case the OfficialWord found by the `where` argument doesn't exist, create a new OfficialWord with this data.
   */
  create: Prisma.XOR<Prisma.OfficialWordCreateInput, Prisma.OfficialWordUncheckedCreateInput>
  /**
   * In case the OfficialWord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OfficialWordUpdateInput, Prisma.OfficialWordUncheckedUpdateInput>
}

/**
 * OfficialWord delete
 */
export type OfficialWordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
  /**
   * Filter which OfficialWord to delete.
   */
  where: Prisma.OfficialWordWhereUniqueInput
}

/**
 * OfficialWord deleteMany
 */
export type OfficialWordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OfficialWords to delete
   */
  where?: Prisma.OfficialWordWhereInput
  /**
   * Limit how many OfficialWords to delete.
   */
  limit?: number
}

/**
 * OfficialWord.translations
 */
export type OfficialWord$translationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialTranslationWord
   */
  select?: Prisma.OfficialTranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialTranslationWord
   */
  omit?: Prisma.OfficialTranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialTranslationWordInclude<ExtArgs> | null
  where?: Prisma.OfficialTranslationWordWhereInput
  orderBy?: Prisma.OfficialTranslationWordOrderByWithRelationInput | Prisma.OfficialTranslationWordOrderByWithRelationInput[]
  cursor?: Prisma.OfficialTranslationWordWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OfficialTranslationWordScalarFieldEnum | Prisma.OfficialTranslationWordScalarFieldEnum[]
}

/**
 * OfficialWord without action
 */
export type OfficialWordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OfficialWord
   */
  select?: Prisma.OfficialWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OfficialWord
   */
  omit?: Prisma.OfficialWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OfficialWordInclude<ExtArgs> | null
}
