
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TranslationWord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TranslationWord
 * 
 */
export type TranslationWordModel = runtime.Types.Result.DefaultSelection<Prisma.$TranslationWordPayload>

export type AggregateTranslationWord = {
  _count: TranslationWordCountAggregateOutputType | null
  _min: TranslationWordMinAggregateOutputType | null
  _max: TranslationWordMaxAggregateOutputType | null
}

export type TranslationWordMinAggregateOutputType = {
  id: string | null
  text: string | null
  language: string | null
  note: string | null
  wordId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TranslationWordMaxAggregateOutputType = {
  id: string | null
  text: string | null
  language: string | null
  note: string | null
  wordId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TranslationWordCountAggregateOutputType = {
  id: number
  text: number
  language: number
  note: number
  wordId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TranslationWordMinAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  wordId?: true
  createdAt?: true
  updatedAt?: true
}

export type TranslationWordMaxAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  wordId?: true
  createdAt?: true
  updatedAt?: true
}

export type TranslationWordCountAggregateInputType = {
  id?: true
  text?: true
  language?: true
  note?: true
  wordId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TranslationWordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TranslationWord to aggregate.
   */
  where?: Prisma.TranslationWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationWords to fetch.
   */
  orderBy?: Prisma.TranslationWordOrderByWithRelationInput | Prisma.TranslationWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TranslationWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TranslationWords
  **/
  _count?: true | TranslationWordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TranslationWordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TranslationWordMaxAggregateInputType
}

export type GetTranslationWordAggregateType<T extends TranslationWordAggregateArgs> = {
      [P in keyof T & keyof AggregateTranslationWord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTranslationWord[P]>
    : Prisma.GetScalarType<T[P], AggregateTranslationWord[P]>
}




export type TranslationWordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TranslationWordWhereInput
  orderBy?: Prisma.TranslationWordOrderByWithAggregationInput | Prisma.TranslationWordOrderByWithAggregationInput[]
  by: Prisma.TranslationWordScalarFieldEnum[] | Prisma.TranslationWordScalarFieldEnum
  having?: Prisma.TranslationWordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TranslationWordCountAggregateInputType | true
  _min?: TranslationWordMinAggregateInputType
  _max?: TranslationWordMaxAggregateInputType
}

export type TranslationWordGroupByOutputType = {
  id: string
  text: string
  language: string
  note: string | null
  wordId: string
  createdAt: Date
  updatedAt: Date
  _count: TranslationWordCountAggregateOutputType | null
  _min: TranslationWordMinAggregateOutputType | null
  _max: TranslationWordMaxAggregateOutputType | null
}

export type GetTranslationWordGroupByPayload<T extends TranslationWordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TranslationWordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TranslationWordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TranslationWordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TranslationWordGroupByOutputType[P]>
      }
    >
  >



export type TranslationWordWhereInput = {
  AND?: Prisma.TranslationWordWhereInput | Prisma.TranslationWordWhereInput[]
  OR?: Prisma.TranslationWordWhereInput[]
  NOT?: Prisma.TranslationWordWhereInput | Prisma.TranslationWordWhereInput[]
  id?: Prisma.StringFilter<"TranslationWord"> | string
  text?: Prisma.StringFilter<"TranslationWord"> | string
  language?: Prisma.StringFilter<"TranslationWord"> | string
  note?: Prisma.StringNullableFilter<"TranslationWord"> | string | null
  wordId?: Prisma.StringFilter<"TranslationWord"> | string
  createdAt?: Prisma.DateTimeFilter<"TranslationWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TranslationWord"> | Date | string
  word?: Prisma.XOR<Prisma.WordScalarRelationFilter, Prisma.WordWhereInput>
}

export type TranslationWordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  word?: Prisma.WordOrderByWithRelationInput
}

export type TranslationWordWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TranslationWordWhereInput | Prisma.TranslationWordWhereInput[]
  OR?: Prisma.TranslationWordWhereInput[]
  NOT?: Prisma.TranslationWordWhereInput | Prisma.TranslationWordWhereInput[]
  text?: Prisma.StringFilter<"TranslationWord"> | string
  language?: Prisma.StringFilter<"TranslationWord"> | string
  note?: Prisma.StringNullableFilter<"TranslationWord"> | string | null
  wordId?: Prisma.StringFilter<"TranslationWord"> | string
  createdAt?: Prisma.DateTimeFilter<"TranslationWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TranslationWord"> | Date | string
  word?: Prisma.XOR<Prisma.WordScalarRelationFilter, Prisma.WordWhereInput>
}, "id">

export type TranslationWordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TranslationWordCountOrderByAggregateInput
  _max?: Prisma.TranslationWordMaxOrderByAggregateInput
  _min?: Prisma.TranslationWordMinOrderByAggregateInput
}

export type TranslationWordScalarWhereWithAggregatesInput = {
  AND?: Prisma.TranslationWordScalarWhereWithAggregatesInput | Prisma.TranslationWordScalarWhereWithAggregatesInput[]
  OR?: Prisma.TranslationWordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TranslationWordScalarWhereWithAggregatesInput | Prisma.TranslationWordScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TranslationWord"> | string
  text?: Prisma.StringWithAggregatesFilter<"TranslationWord"> | string
  language?: Prisma.StringWithAggregatesFilter<"TranslationWord"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"TranslationWord"> | string | null
  wordId?: Prisma.StringWithAggregatesFilter<"TranslationWord"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TranslationWord"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TranslationWord"> | Date | string
}

export type TranslationWordCreateInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  word: Prisma.WordCreateNestedOneWithoutTranslationsWordsInput
}

export type TranslationWordUncheckedCreateInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  wordId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationWordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  word?: Prisma.WordUpdateOneRequiredWithoutTranslationsWordsNestedInput
}

export type TranslationWordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wordId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationWordCreateManyInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  wordId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationWordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationWordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  wordId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationWordListRelationFilter = {
  every?: Prisma.TranslationWordWhereInput
  some?: Prisma.TranslationWordWhereInput
  none?: Prisma.TranslationWordWhereInput
}

export type TranslationWordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TranslationWordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationWordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationWordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  text?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  wordId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationWordCreateNestedManyWithoutWordInput = {
  create?: Prisma.XOR<Prisma.TranslationWordCreateWithoutWordInput, Prisma.TranslationWordUncheckedCreateWithoutWordInput> | Prisma.TranslationWordCreateWithoutWordInput[] | Prisma.TranslationWordUncheckedCreateWithoutWordInput[]
  connectOrCreate?: Prisma.TranslationWordCreateOrConnectWithoutWordInput | Prisma.TranslationWordCreateOrConnectWithoutWordInput[]
  createMany?: Prisma.TranslationWordCreateManyWordInputEnvelope
  connect?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
}

export type TranslationWordUncheckedCreateNestedManyWithoutWordInput = {
  create?: Prisma.XOR<Prisma.TranslationWordCreateWithoutWordInput, Prisma.TranslationWordUncheckedCreateWithoutWordInput> | Prisma.TranslationWordCreateWithoutWordInput[] | Prisma.TranslationWordUncheckedCreateWithoutWordInput[]
  connectOrCreate?: Prisma.TranslationWordCreateOrConnectWithoutWordInput | Prisma.TranslationWordCreateOrConnectWithoutWordInput[]
  createMany?: Prisma.TranslationWordCreateManyWordInputEnvelope
  connect?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
}

export type TranslationWordUpdateManyWithoutWordNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationWordCreateWithoutWordInput, Prisma.TranslationWordUncheckedCreateWithoutWordInput> | Prisma.TranslationWordCreateWithoutWordInput[] | Prisma.TranslationWordUncheckedCreateWithoutWordInput[]
  connectOrCreate?: Prisma.TranslationWordCreateOrConnectWithoutWordInput | Prisma.TranslationWordCreateOrConnectWithoutWordInput[]
  upsert?: Prisma.TranslationWordUpsertWithWhereUniqueWithoutWordInput | Prisma.TranslationWordUpsertWithWhereUniqueWithoutWordInput[]
  createMany?: Prisma.TranslationWordCreateManyWordInputEnvelope
  set?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
  disconnect?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
  delete?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
  connect?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
  update?: Prisma.TranslationWordUpdateWithWhereUniqueWithoutWordInput | Prisma.TranslationWordUpdateWithWhereUniqueWithoutWordInput[]
  updateMany?: Prisma.TranslationWordUpdateManyWithWhereWithoutWordInput | Prisma.TranslationWordUpdateManyWithWhereWithoutWordInput[]
  deleteMany?: Prisma.TranslationWordScalarWhereInput | Prisma.TranslationWordScalarWhereInput[]
}

export type TranslationWordUncheckedUpdateManyWithoutWordNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationWordCreateWithoutWordInput, Prisma.TranslationWordUncheckedCreateWithoutWordInput> | Prisma.TranslationWordCreateWithoutWordInput[] | Prisma.TranslationWordUncheckedCreateWithoutWordInput[]
  connectOrCreate?: Prisma.TranslationWordCreateOrConnectWithoutWordInput | Prisma.TranslationWordCreateOrConnectWithoutWordInput[]
  upsert?: Prisma.TranslationWordUpsertWithWhereUniqueWithoutWordInput | Prisma.TranslationWordUpsertWithWhereUniqueWithoutWordInput[]
  createMany?: Prisma.TranslationWordCreateManyWordInputEnvelope
  set?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
  disconnect?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
  delete?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
  connect?: Prisma.TranslationWordWhereUniqueInput | Prisma.TranslationWordWhereUniqueInput[]
  update?: Prisma.TranslationWordUpdateWithWhereUniqueWithoutWordInput | Prisma.TranslationWordUpdateWithWhereUniqueWithoutWordInput[]
  updateMany?: Prisma.TranslationWordUpdateManyWithWhereWithoutWordInput | Prisma.TranslationWordUpdateManyWithWhereWithoutWordInput[]
  deleteMany?: Prisma.TranslationWordScalarWhereInput | Prisma.TranslationWordScalarWhereInput[]
}

export type TranslationWordCreateWithoutWordInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationWordUncheckedCreateWithoutWordInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationWordCreateOrConnectWithoutWordInput = {
  where: Prisma.TranslationWordWhereUniqueInput
  create: Prisma.XOR<Prisma.TranslationWordCreateWithoutWordInput, Prisma.TranslationWordUncheckedCreateWithoutWordInput>
}

export type TranslationWordCreateManyWordInputEnvelope = {
  data: Prisma.TranslationWordCreateManyWordInput | Prisma.TranslationWordCreateManyWordInput[]
  skipDuplicates?: boolean
}

export type TranslationWordUpsertWithWhereUniqueWithoutWordInput = {
  where: Prisma.TranslationWordWhereUniqueInput
  update: Prisma.XOR<Prisma.TranslationWordUpdateWithoutWordInput, Prisma.TranslationWordUncheckedUpdateWithoutWordInput>
  create: Prisma.XOR<Prisma.TranslationWordCreateWithoutWordInput, Prisma.TranslationWordUncheckedCreateWithoutWordInput>
}

export type TranslationWordUpdateWithWhereUniqueWithoutWordInput = {
  where: Prisma.TranslationWordWhereUniqueInput
  data: Prisma.XOR<Prisma.TranslationWordUpdateWithoutWordInput, Prisma.TranslationWordUncheckedUpdateWithoutWordInput>
}

export type TranslationWordUpdateManyWithWhereWithoutWordInput = {
  where: Prisma.TranslationWordScalarWhereInput
  data: Prisma.XOR<Prisma.TranslationWordUpdateManyMutationInput, Prisma.TranslationWordUncheckedUpdateManyWithoutWordInput>
}

export type TranslationWordScalarWhereInput = {
  AND?: Prisma.TranslationWordScalarWhereInput | Prisma.TranslationWordScalarWhereInput[]
  OR?: Prisma.TranslationWordScalarWhereInput[]
  NOT?: Prisma.TranslationWordScalarWhereInput | Prisma.TranslationWordScalarWhereInput[]
  id?: Prisma.StringFilter<"TranslationWord"> | string
  text?: Prisma.StringFilter<"TranslationWord"> | string
  language?: Prisma.StringFilter<"TranslationWord"> | string
  note?: Prisma.StringNullableFilter<"TranslationWord"> | string | null
  wordId?: Prisma.StringFilter<"TranslationWord"> | string
  createdAt?: Prisma.DateTimeFilter<"TranslationWord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TranslationWord"> | Date | string
}

export type TranslationWordCreateManyWordInput = {
  id?: string
  text: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationWordUpdateWithoutWordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationWordUncheckedUpdateWithoutWordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationWordUncheckedUpdateManyWithoutWordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TranslationWordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  wordId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  word?: boolean | Prisma.WordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationWord"]>

export type TranslationWordSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  wordId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  word?: boolean | Prisma.WordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationWord"]>

export type TranslationWordSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  wordId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  word?: boolean | Prisma.WordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationWord"]>

export type TranslationWordSelectScalar = {
  id?: boolean
  text?: boolean
  language?: boolean
  note?: boolean
  wordId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TranslationWordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "text" | "language" | "note" | "wordId" | "createdAt" | "updatedAt", ExtArgs["result"]["translationWord"]>
export type TranslationWordInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  word?: boolean | Prisma.WordDefaultArgs<ExtArgs>
}
export type TranslationWordIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  word?: boolean | Prisma.WordDefaultArgs<ExtArgs>
}
export type TranslationWordIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  word?: boolean | Prisma.WordDefaultArgs<ExtArgs>
}

export type $TranslationWordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TranslationWord"
  objects: {
    word: Prisma.$WordPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    text: string
    language: string
    note: string | null
    wordId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["translationWord"]>
  composites: {}
}

export type TranslationWordGetPayload<S extends boolean | null | undefined | TranslationWordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload, S>

export type TranslationWordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TranslationWordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TranslationWordCountAggregateInputType | true
  }

export interface TranslationWordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TranslationWord'], meta: { name: 'TranslationWord' } }
  /**
   * Find zero or one TranslationWord that matches the filter.
   * @param {TranslationWordFindUniqueArgs} args - Arguments to find a TranslationWord
   * @example
   * // Get one TranslationWord
   * const translationWord = await prisma.translationWord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TranslationWordFindUniqueArgs>(args: Prisma.SelectSubset<T, TranslationWordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TranslationWordClient<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TranslationWord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TranslationWordFindUniqueOrThrowArgs} args - Arguments to find a TranslationWord
   * @example
   * // Get one TranslationWord
   * const translationWord = await prisma.translationWord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TranslationWordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TranslationWordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationWordClient<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TranslationWord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationWordFindFirstArgs} args - Arguments to find a TranslationWord
   * @example
   * // Get one TranslationWord
   * const translationWord = await prisma.translationWord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TranslationWordFindFirstArgs>(args?: Prisma.SelectSubset<T, TranslationWordFindFirstArgs<ExtArgs>>): Prisma.Prisma__TranslationWordClient<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TranslationWord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationWordFindFirstOrThrowArgs} args - Arguments to find a TranslationWord
   * @example
   * // Get one TranslationWord
   * const translationWord = await prisma.translationWord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TranslationWordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TranslationWordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationWordClient<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TranslationWords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationWordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TranslationWords
   * const translationWords = await prisma.translationWord.findMany()
   * 
   * // Get first 10 TranslationWords
   * const translationWords = await prisma.translationWord.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const translationWordWithIdOnly = await prisma.translationWord.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TranslationWordFindManyArgs>(args?: Prisma.SelectSubset<T, TranslationWordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TranslationWord.
   * @param {TranslationWordCreateArgs} args - Arguments to create a TranslationWord.
   * @example
   * // Create one TranslationWord
   * const TranslationWord = await prisma.translationWord.create({
   *   data: {
   *     // ... data to create a TranslationWord
   *   }
   * })
   * 
   */
  create<T extends TranslationWordCreateArgs>(args: Prisma.SelectSubset<T, TranslationWordCreateArgs<ExtArgs>>): Prisma.Prisma__TranslationWordClient<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TranslationWords.
   * @param {TranslationWordCreateManyArgs} args - Arguments to create many TranslationWords.
   * @example
   * // Create many TranslationWords
   * const translationWord = await prisma.translationWord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TranslationWordCreateManyArgs>(args?: Prisma.SelectSubset<T, TranslationWordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TranslationWords and returns the data saved in the database.
   * @param {TranslationWordCreateManyAndReturnArgs} args - Arguments to create many TranslationWords.
   * @example
   * // Create many TranslationWords
   * const translationWord = await prisma.translationWord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TranslationWords and only return the `id`
   * const translationWordWithIdOnly = await prisma.translationWord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TranslationWordCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TranslationWordCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TranslationWord.
   * @param {TranslationWordDeleteArgs} args - Arguments to delete one TranslationWord.
   * @example
   * // Delete one TranslationWord
   * const TranslationWord = await prisma.translationWord.delete({
   *   where: {
   *     // ... filter to delete one TranslationWord
   *   }
   * })
   * 
   */
  delete<T extends TranslationWordDeleteArgs>(args: Prisma.SelectSubset<T, TranslationWordDeleteArgs<ExtArgs>>): Prisma.Prisma__TranslationWordClient<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TranslationWord.
   * @param {TranslationWordUpdateArgs} args - Arguments to update one TranslationWord.
   * @example
   * // Update one TranslationWord
   * const translationWord = await prisma.translationWord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TranslationWordUpdateArgs>(args: Prisma.SelectSubset<T, TranslationWordUpdateArgs<ExtArgs>>): Prisma.Prisma__TranslationWordClient<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TranslationWords.
   * @param {TranslationWordDeleteManyArgs} args - Arguments to filter TranslationWords to delete.
   * @example
   * // Delete a few TranslationWords
   * const { count } = await prisma.translationWord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TranslationWordDeleteManyArgs>(args?: Prisma.SelectSubset<T, TranslationWordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TranslationWords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationWordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TranslationWords
   * const translationWord = await prisma.translationWord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TranslationWordUpdateManyArgs>(args: Prisma.SelectSubset<T, TranslationWordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TranslationWords and returns the data updated in the database.
   * @param {TranslationWordUpdateManyAndReturnArgs} args - Arguments to update many TranslationWords.
   * @example
   * // Update many TranslationWords
   * const translationWord = await prisma.translationWord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TranslationWords and only return the `id`
   * const translationWordWithIdOnly = await prisma.translationWord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TranslationWordUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TranslationWordUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TranslationWord.
   * @param {TranslationWordUpsertArgs} args - Arguments to update or create a TranslationWord.
   * @example
   * // Update or create a TranslationWord
   * const translationWord = await prisma.translationWord.upsert({
   *   create: {
   *     // ... data to create a TranslationWord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TranslationWord we want to update
   *   }
   * })
   */
  upsert<T extends TranslationWordUpsertArgs>(args: Prisma.SelectSubset<T, TranslationWordUpsertArgs<ExtArgs>>): Prisma.Prisma__TranslationWordClient<runtime.Types.Result.GetResult<Prisma.$TranslationWordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TranslationWords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationWordCountArgs} args - Arguments to filter TranslationWords to count.
   * @example
   * // Count the number of TranslationWords
   * const count = await prisma.translationWord.count({
   *   where: {
   *     // ... the filter for the TranslationWords we want to count
   *   }
   * })
  **/
  count<T extends TranslationWordCountArgs>(
    args?: Prisma.Subset<T, TranslationWordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TranslationWordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TranslationWord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationWordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TranslationWordAggregateArgs>(args: Prisma.Subset<T, TranslationWordAggregateArgs>): Prisma.PrismaPromise<GetTranslationWordAggregateType<T>>

  /**
   * Group by TranslationWord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationWordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TranslationWordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TranslationWordGroupByArgs['orderBy'] }
      : { orderBy?: TranslationWordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TranslationWordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTranslationWordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TranslationWord model
 */
readonly fields: TranslationWordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TranslationWord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TranslationWordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  word<T extends Prisma.WordDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WordDefaultArgs<ExtArgs>>): Prisma.Prisma__WordClient<runtime.Types.Result.GetResult<Prisma.$WordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TranslationWord model
 */
export interface TranslationWordFieldRefs {
  readonly id: Prisma.FieldRef<"TranslationWord", 'String'>
  readonly text: Prisma.FieldRef<"TranslationWord", 'String'>
  readonly language: Prisma.FieldRef<"TranslationWord", 'String'>
  readonly note: Prisma.FieldRef<"TranslationWord", 'String'>
  readonly wordId: Prisma.FieldRef<"TranslationWord", 'String'>
  readonly createdAt: Prisma.FieldRef<"TranslationWord", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TranslationWord", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TranslationWord findUnique
 */
export type TranslationWordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which TranslationWord to fetch.
   */
  where: Prisma.TranslationWordWhereUniqueInput
}

/**
 * TranslationWord findUniqueOrThrow
 */
export type TranslationWordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which TranslationWord to fetch.
   */
  where: Prisma.TranslationWordWhereUniqueInput
}

/**
 * TranslationWord findFirst
 */
export type TranslationWordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which TranslationWord to fetch.
   */
  where?: Prisma.TranslationWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationWords to fetch.
   */
  orderBy?: Prisma.TranslationWordOrderByWithRelationInput | Prisma.TranslationWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TranslationWords.
   */
  cursor?: Prisma.TranslationWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationWords.
   */
  distinct?: Prisma.TranslationWordScalarFieldEnum | Prisma.TranslationWordScalarFieldEnum[]
}

/**
 * TranslationWord findFirstOrThrow
 */
export type TranslationWordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which TranslationWord to fetch.
   */
  where?: Prisma.TranslationWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationWords to fetch.
   */
  orderBy?: Prisma.TranslationWordOrderByWithRelationInput | Prisma.TranslationWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TranslationWords.
   */
  cursor?: Prisma.TranslationWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationWords.
   */
  distinct?: Prisma.TranslationWordScalarFieldEnum | Prisma.TranslationWordScalarFieldEnum[]
}

/**
 * TranslationWord findMany
 */
export type TranslationWordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * Filter, which TranslationWords to fetch.
   */
  where?: Prisma.TranslationWordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationWords to fetch.
   */
  orderBy?: Prisma.TranslationWordOrderByWithRelationInput | Prisma.TranslationWordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TranslationWords.
   */
  cursor?: Prisma.TranslationWordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationWords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationWords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationWords.
   */
  distinct?: Prisma.TranslationWordScalarFieldEnum | Prisma.TranslationWordScalarFieldEnum[]
}

/**
 * TranslationWord create
 */
export type TranslationWordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * The data needed to create a TranslationWord.
   */
  data: Prisma.XOR<Prisma.TranslationWordCreateInput, Prisma.TranslationWordUncheckedCreateInput>
}

/**
 * TranslationWord createMany
 */
export type TranslationWordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TranslationWords.
   */
  data: Prisma.TranslationWordCreateManyInput | Prisma.TranslationWordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TranslationWord createManyAndReturn
 */
export type TranslationWordCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * The data used to create many TranslationWords.
   */
  data: Prisma.TranslationWordCreateManyInput | Prisma.TranslationWordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TranslationWord update
 */
export type TranslationWordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * The data needed to update a TranslationWord.
   */
  data: Prisma.XOR<Prisma.TranslationWordUpdateInput, Prisma.TranslationWordUncheckedUpdateInput>
  /**
   * Choose, which TranslationWord to update.
   */
  where: Prisma.TranslationWordWhereUniqueInput
}

/**
 * TranslationWord updateMany
 */
export type TranslationWordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TranslationWords.
   */
  data: Prisma.XOR<Prisma.TranslationWordUpdateManyMutationInput, Prisma.TranslationWordUncheckedUpdateManyInput>
  /**
   * Filter which TranslationWords to update
   */
  where?: Prisma.TranslationWordWhereInput
  /**
   * Limit how many TranslationWords to update.
   */
  limit?: number
}

/**
 * TranslationWord updateManyAndReturn
 */
export type TranslationWordUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * The data used to update TranslationWords.
   */
  data: Prisma.XOR<Prisma.TranslationWordUpdateManyMutationInput, Prisma.TranslationWordUncheckedUpdateManyInput>
  /**
   * Filter which TranslationWords to update
   */
  where?: Prisma.TranslationWordWhereInput
  /**
   * Limit how many TranslationWords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TranslationWord upsert
 */
export type TranslationWordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * The filter to search for the TranslationWord to update in case it exists.
   */
  where: Prisma.TranslationWordWhereUniqueInput
  /**
   * In case the TranslationWord found by the `where` argument doesn't exist, create a new TranslationWord with this data.
   */
  create: Prisma.XOR<Prisma.TranslationWordCreateInput, Prisma.TranslationWordUncheckedCreateInput>
  /**
   * In case the TranslationWord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TranslationWordUpdateInput, Prisma.TranslationWordUncheckedUpdateInput>
}

/**
 * TranslationWord delete
 */
export type TranslationWordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
  /**
   * Filter which TranslationWord to delete.
   */
  where: Prisma.TranslationWordWhereUniqueInput
}

/**
 * TranslationWord deleteMany
 */
export type TranslationWordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TranslationWords to delete
   */
  where?: Prisma.TranslationWordWhereInput
  /**
   * Limit how many TranslationWords to delete.
   */
  limit?: number
}

/**
 * TranslationWord without action
 */
export type TranslationWordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationWord
   */
  select?: Prisma.TranslationWordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationWord
   */
  omit?: Prisma.TranslationWordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationWordInclude<ExtArgs> | null
}
