
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TranslationLists` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TranslationLists
 * 
 */
export type TranslationListsModel = runtime.Types.Result.DefaultSelection<Prisma.$TranslationListsPayload>

export type AggregateTranslationLists = {
  _count: TranslationListsCountAggregateOutputType | null
  _min: TranslationListsMinAggregateOutputType | null
  _max: TranslationListsMaxAggregateOutputType | null
}

export type TranslationListsMinAggregateOutputType = {
  id: string | null
  language: string | null
  note: string | null
  listId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TranslationListsMaxAggregateOutputType = {
  id: string | null
  language: string | null
  note: string | null
  listId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TranslationListsCountAggregateOutputType = {
  id: number
  language: number
  note: number
  listId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TranslationListsMinAggregateInputType = {
  id?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
}

export type TranslationListsMaxAggregateInputType = {
  id?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
}

export type TranslationListsCountAggregateInputType = {
  id?: true
  language?: true
  note?: true
  listId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TranslationListsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TranslationLists to aggregate.
   */
  where?: Prisma.TranslationListsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationLists to fetch.
   */
  orderBy?: Prisma.TranslationListsOrderByWithRelationInput | Prisma.TranslationListsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TranslationListsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TranslationLists
  **/
  _count?: true | TranslationListsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TranslationListsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TranslationListsMaxAggregateInputType
}

export type GetTranslationListsAggregateType<T extends TranslationListsAggregateArgs> = {
      [P in keyof T & keyof AggregateTranslationLists]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTranslationLists[P]>
    : Prisma.GetScalarType<T[P], AggregateTranslationLists[P]>
}




export type TranslationListsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TranslationListsWhereInput
  orderBy?: Prisma.TranslationListsOrderByWithAggregationInput | Prisma.TranslationListsOrderByWithAggregationInput[]
  by: Prisma.TranslationListsScalarFieldEnum[] | Prisma.TranslationListsScalarFieldEnum
  having?: Prisma.TranslationListsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TranslationListsCountAggregateInputType | true
  _min?: TranslationListsMinAggregateInputType
  _max?: TranslationListsMaxAggregateInputType
}

export type TranslationListsGroupByOutputType = {
  id: string
  language: string
  note: string | null
  listId: string
  createdAt: Date
  updatedAt: Date
  _count: TranslationListsCountAggregateOutputType | null
  _min: TranslationListsMinAggregateOutputType | null
  _max: TranslationListsMaxAggregateOutputType | null
}

export type GetTranslationListsGroupByPayload<T extends TranslationListsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TranslationListsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TranslationListsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TranslationListsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TranslationListsGroupByOutputType[P]>
      }
    >
  >



export type TranslationListsWhereInput = {
  AND?: Prisma.TranslationListsWhereInput | Prisma.TranslationListsWhereInput[]
  OR?: Prisma.TranslationListsWhereInput[]
  NOT?: Prisma.TranslationListsWhereInput | Prisma.TranslationListsWhereInput[]
  id?: Prisma.StringFilter<"TranslationLists"> | string
  language?: Prisma.StringFilter<"TranslationLists"> | string
  note?: Prisma.StringNullableFilter<"TranslationLists"> | string | null
  listId?: Prisma.StringFilter<"TranslationLists"> | string
  createdAt?: Prisma.DateTimeFilter<"TranslationLists"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TranslationLists"> | Date | string
  list?: Prisma.XOR<Prisma.ListScalarRelationFilter, Prisma.ListWhereInput>
}

export type TranslationListsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  list?: Prisma.ListOrderByWithRelationInput
}

export type TranslationListsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TranslationListsWhereInput | Prisma.TranslationListsWhereInput[]
  OR?: Prisma.TranslationListsWhereInput[]
  NOT?: Prisma.TranslationListsWhereInput | Prisma.TranslationListsWhereInput[]
  language?: Prisma.StringFilter<"TranslationLists"> | string
  note?: Prisma.StringNullableFilter<"TranslationLists"> | string | null
  listId?: Prisma.StringFilter<"TranslationLists"> | string
  createdAt?: Prisma.DateTimeFilter<"TranslationLists"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TranslationLists"> | Date | string
  list?: Prisma.XOR<Prisma.ListScalarRelationFilter, Prisma.ListWhereInput>
}, "id">

export type TranslationListsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TranslationListsCountOrderByAggregateInput
  _max?: Prisma.TranslationListsMaxOrderByAggregateInput
  _min?: Prisma.TranslationListsMinOrderByAggregateInput
}

export type TranslationListsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TranslationListsScalarWhereWithAggregatesInput | Prisma.TranslationListsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TranslationListsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TranslationListsScalarWhereWithAggregatesInput | Prisma.TranslationListsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TranslationLists"> | string
  language?: Prisma.StringWithAggregatesFilter<"TranslationLists"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"TranslationLists"> | string | null
  listId?: Prisma.StringWithAggregatesFilter<"TranslationLists"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TranslationLists"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TranslationLists"> | Date | string
}

export type TranslationListsCreateInput = {
  id?: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.ListCreateNestedOneWithoutTranslationListsInput
}

export type TranslationListsUncheckedCreateInput = {
  id?: string
  language: string
  note?: string | null
  listId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationListsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.ListUpdateOneRequiredWithoutTranslationListsNestedInput
}

export type TranslationListsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationListsCreateManyInput = {
  id?: string
  language: string
  note?: string | null
  listId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationListsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationListsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationListsListRelationFilter = {
  every?: Prisma.TranslationListsWhereInput
  some?: Prisma.TranslationListsWhereInput
  none?: Prisma.TranslationListsWhereInput
}

export type TranslationListsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TranslationListsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationListsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationListsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  note?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TranslationListsCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.TranslationListsCreateWithoutListInput, Prisma.TranslationListsUncheckedCreateWithoutListInput> | Prisma.TranslationListsCreateWithoutListInput[] | Prisma.TranslationListsUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.TranslationListsCreateOrConnectWithoutListInput | Prisma.TranslationListsCreateOrConnectWithoutListInput[]
  createMany?: Prisma.TranslationListsCreateManyListInputEnvelope
  connect?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
}

export type TranslationListsUncheckedCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.TranslationListsCreateWithoutListInput, Prisma.TranslationListsUncheckedCreateWithoutListInput> | Prisma.TranslationListsCreateWithoutListInput[] | Prisma.TranslationListsUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.TranslationListsCreateOrConnectWithoutListInput | Prisma.TranslationListsCreateOrConnectWithoutListInput[]
  createMany?: Prisma.TranslationListsCreateManyListInputEnvelope
  connect?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
}

export type TranslationListsUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationListsCreateWithoutListInput, Prisma.TranslationListsUncheckedCreateWithoutListInput> | Prisma.TranslationListsCreateWithoutListInput[] | Prisma.TranslationListsUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.TranslationListsCreateOrConnectWithoutListInput | Prisma.TranslationListsCreateOrConnectWithoutListInput[]
  upsert?: Prisma.TranslationListsUpsertWithWhereUniqueWithoutListInput | Prisma.TranslationListsUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.TranslationListsCreateManyListInputEnvelope
  set?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
  disconnect?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
  delete?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
  connect?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
  update?: Prisma.TranslationListsUpdateWithWhereUniqueWithoutListInput | Prisma.TranslationListsUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.TranslationListsUpdateManyWithWhereWithoutListInput | Prisma.TranslationListsUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.TranslationListsScalarWhereInput | Prisma.TranslationListsScalarWhereInput[]
}

export type TranslationListsUncheckedUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.TranslationListsCreateWithoutListInput, Prisma.TranslationListsUncheckedCreateWithoutListInput> | Prisma.TranslationListsCreateWithoutListInput[] | Prisma.TranslationListsUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.TranslationListsCreateOrConnectWithoutListInput | Prisma.TranslationListsCreateOrConnectWithoutListInput[]
  upsert?: Prisma.TranslationListsUpsertWithWhereUniqueWithoutListInput | Prisma.TranslationListsUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.TranslationListsCreateManyListInputEnvelope
  set?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
  disconnect?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
  delete?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
  connect?: Prisma.TranslationListsWhereUniqueInput | Prisma.TranslationListsWhereUniqueInput[]
  update?: Prisma.TranslationListsUpdateWithWhereUniqueWithoutListInput | Prisma.TranslationListsUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.TranslationListsUpdateManyWithWhereWithoutListInput | Prisma.TranslationListsUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.TranslationListsScalarWhereInput | Prisma.TranslationListsScalarWhereInput[]
}

export type TranslationListsCreateWithoutListInput = {
  id?: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationListsUncheckedCreateWithoutListInput = {
  id?: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationListsCreateOrConnectWithoutListInput = {
  where: Prisma.TranslationListsWhereUniqueInput
  create: Prisma.XOR<Prisma.TranslationListsCreateWithoutListInput, Prisma.TranslationListsUncheckedCreateWithoutListInput>
}

export type TranslationListsCreateManyListInputEnvelope = {
  data: Prisma.TranslationListsCreateManyListInput | Prisma.TranslationListsCreateManyListInput[]
  skipDuplicates?: boolean
}

export type TranslationListsUpsertWithWhereUniqueWithoutListInput = {
  where: Prisma.TranslationListsWhereUniqueInput
  update: Prisma.XOR<Prisma.TranslationListsUpdateWithoutListInput, Prisma.TranslationListsUncheckedUpdateWithoutListInput>
  create: Prisma.XOR<Prisma.TranslationListsCreateWithoutListInput, Prisma.TranslationListsUncheckedCreateWithoutListInput>
}

export type TranslationListsUpdateWithWhereUniqueWithoutListInput = {
  where: Prisma.TranslationListsWhereUniqueInput
  data: Prisma.XOR<Prisma.TranslationListsUpdateWithoutListInput, Prisma.TranslationListsUncheckedUpdateWithoutListInput>
}

export type TranslationListsUpdateManyWithWhereWithoutListInput = {
  where: Prisma.TranslationListsScalarWhereInput
  data: Prisma.XOR<Prisma.TranslationListsUpdateManyMutationInput, Prisma.TranslationListsUncheckedUpdateManyWithoutListInput>
}

export type TranslationListsScalarWhereInput = {
  AND?: Prisma.TranslationListsScalarWhereInput | Prisma.TranslationListsScalarWhereInput[]
  OR?: Prisma.TranslationListsScalarWhereInput[]
  NOT?: Prisma.TranslationListsScalarWhereInput | Prisma.TranslationListsScalarWhereInput[]
  id?: Prisma.StringFilter<"TranslationLists"> | string
  language?: Prisma.StringFilter<"TranslationLists"> | string
  note?: Prisma.StringNullableFilter<"TranslationLists"> | string | null
  listId?: Prisma.StringFilter<"TranslationLists"> | string
  createdAt?: Prisma.DateTimeFilter<"TranslationLists"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TranslationLists"> | Date | string
}

export type TranslationListsCreateManyListInput = {
  id?: string
  language: string
  note?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TranslationListsUpdateWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationListsUncheckedUpdateWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TranslationListsUncheckedUpdateManyWithoutListInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TranslationListsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationLists"]>

export type TranslationListsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationLists"]>

export type TranslationListsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["translationLists"]>

export type TranslationListsSelectScalar = {
  id?: boolean
  language?: boolean
  note?: boolean
  listId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TranslationListsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "language" | "note" | "listId" | "createdAt" | "updatedAt", ExtArgs["result"]["translationLists"]>
export type TranslationListsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}
export type TranslationListsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}
export type TranslationListsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}

export type $TranslationListsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TranslationLists"
  objects: {
    list: Prisma.$ListPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    language: string
    note: string | null
    listId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["translationLists"]>
  composites: {}
}

export type TranslationListsGetPayload<S extends boolean | null | undefined | TranslationListsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload, S>

export type TranslationListsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TranslationListsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TranslationListsCountAggregateInputType | true
  }

export interface TranslationListsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TranslationLists'], meta: { name: 'TranslationLists' } }
  /**
   * Find zero or one TranslationLists that matches the filter.
   * @param {TranslationListsFindUniqueArgs} args - Arguments to find a TranslationLists
   * @example
   * // Get one TranslationLists
   * const translationLists = await prisma.translationLists.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TranslationListsFindUniqueArgs>(args: Prisma.SelectSubset<T, TranslationListsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TranslationListsClient<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TranslationLists that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TranslationListsFindUniqueOrThrowArgs} args - Arguments to find a TranslationLists
   * @example
   * // Get one TranslationLists
   * const translationLists = await prisma.translationLists.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TranslationListsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TranslationListsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationListsClient<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TranslationLists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationListsFindFirstArgs} args - Arguments to find a TranslationLists
   * @example
   * // Get one TranslationLists
   * const translationLists = await prisma.translationLists.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TranslationListsFindFirstArgs>(args?: Prisma.SelectSubset<T, TranslationListsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TranslationListsClient<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TranslationLists that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationListsFindFirstOrThrowArgs} args - Arguments to find a TranslationLists
   * @example
   * // Get one TranslationLists
   * const translationLists = await prisma.translationLists.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TranslationListsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TranslationListsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TranslationListsClient<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TranslationLists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationListsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TranslationLists
   * const translationLists = await prisma.translationLists.findMany()
   * 
   * // Get first 10 TranslationLists
   * const translationLists = await prisma.translationLists.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const translationListsWithIdOnly = await prisma.translationLists.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TranslationListsFindManyArgs>(args?: Prisma.SelectSubset<T, TranslationListsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TranslationLists.
   * @param {TranslationListsCreateArgs} args - Arguments to create a TranslationLists.
   * @example
   * // Create one TranslationLists
   * const TranslationLists = await prisma.translationLists.create({
   *   data: {
   *     // ... data to create a TranslationLists
   *   }
   * })
   * 
   */
  create<T extends TranslationListsCreateArgs>(args: Prisma.SelectSubset<T, TranslationListsCreateArgs<ExtArgs>>): Prisma.Prisma__TranslationListsClient<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TranslationLists.
   * @param {TranslationListsCreateManyArgs} args - Arguments to create many TranslationLists.
   * @example
   * // Create many TranslationLists
   * const translationLists = await prisma.translationLists.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TranslationListsCreateManyArgs>(args?: Prisma.SelectSubset<T, TranslationListsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TranslationLists and returns the data saved in the database.
   * @param {TranslationListsCreateManyAndReturnArgs} args - Arguments to create many TranslationLists.
   * @example
   * // Create many TranslationLists
   * const translationLists = await prisma.translationLists.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TranslationLists and only return the `id`
   * const translationListsWithIdOnly = await prisma.translationLists.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TranslationListsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TranslationListsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TranslationLists.
   * @param {TranslationListsDeleteArgs} args - Arguments to delete one TranslationLists.
   * @example
   * // Delete one TranslationLists
   * const TranslationLists = await prisma.translationLists.delete({
   *   where: {
   *     // ... filter to delete one TranslationLists
   *   }
   * })
   * 
   */
  delete<T extends TranslationListsDeleteArgs>(args: Prisma.SelectSubset<T, TranslationListsDeleteArgs<ExtArgs>>): Prisma.Prisma__TranslationListsClient<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TranslationLists.
   * @param {TranslationListsUpdateArgs} args - Arguments to update one TranslationLists.
   * @example
   * // Update one TranslationLists
   * const translationLists = await prisma.translationLists.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TranslationListsUpdateArgs>(args: Prisma.SelectSubset<T, TranslationListsUpdateArgs<ExtArgs>>): Prisma.Prisma__TranslationListsClient<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TranslationLists.
   * @param {TranslationListsDeleteManyArgs} args - Arguments to filter TranslationLists to delete.
   * @example
   * // Delete a few TranslationLists
   * const { count } = await prisma.translationLists.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TranslationListsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TranslationListsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TranslationLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationListsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TranslationLists
   * const translationLists = await prisma.translationLists.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TranslationListsUpdateManyArgs>(args: Prisma.SelectSubset<T, TranslationListsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TranslationLists and returns the data updated in the database.
   * @param {TranslationListsUpdateManyAndReturnArgs} args - Arguments to update many TranslationLists.
   * @example
   * // Update many TranslationLists
   * const translationLists = await prisma.translationLists.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TranslationLists and only return the `id`
   * const translationListsWithIdOnly = await prisma.translationLists.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TranslationListsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TranslationListsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TranslationLists.
   * @param {TranslationListsUpsertArgs} args - Arguments to update or create a TranslationLists.
   * @example
   * // Update or create a TranslationLists
   * const translationLists = await prisma.translationLists.upsert({
   *   create: {
   *     // ... data to create a TranslationLists
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TranslationLists we want to update
   *   }
   * })
   */
  upsert<T extends TranslationListsUpsertArgs>(args: Prisma.SelectSubset<T, TranslationListsUpsertArgs<ExtArgs>>): Prisma.Prisma__TranslationListsClient<runtime.Types.Result.GetResult<Prisma.$TranslationListsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TranslationLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationListsCountArgs} args - Arguments to filter TranslationLists to count.
   * @example
   * // Count the number of TranslationLists
   * const count = await prisma.translationLists.count({
   *   where: {
   *     // ... the filter for the TranslationLists we want to count
   *   }
   * })
  **/
  count<T extends TranslationListsCountArgs>(
    args?: Prisma.Subset<T, TranslationListsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TranslationListsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TranslationLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationListsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TranslationListsAggregateArgs>(args: Prisma.Subset<T, TranslationListsAggregateArgs>): Prisma.PrismaPromise<GetTranslationListsAggregateType<T>>

  /**
   * Group by TranslationLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TranslationListsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TranslationListsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TranslationListsGroupByArgs['orderBy'] }
      : { orderBy?: TranslationListsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TranslationListsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTranslationListsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TranslationLists model
 */
readonly fields: TranslationListsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TranslationLists.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TranslationListsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  list<T extends Prisma.ListDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListDefaultArgs<ExtArgs>>): Prisma.Prisma__ListClient<runtime.Types.Result.GetResult<Prisma.$ListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TranslationLists model
 */
export interface TranslationListsFieldRefs {
  readonly id: Prisma.FieldRef<"TranslationLists", 'String'>
  readonly language: Prisma.FieldRef<"TranslationLists", 'String'>
  readonly note: Prisma.FieldRef<"TranslationLists", 'String'>
  readonly listId: Prisma.FieldRef<"TranslationLists", 'String'>
  readonly createdAt: Prisma.FieldRef<"TranslationLists", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TranslationLists", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TranslationLists findUnique
 */
export type TranslationListsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * Filter, which TranslationLists to fetch.
   */
  where: Prisma.TranslationListsWhereUniqueInput
}

/**
 * TranslationLists findUniqueOrThrow
 */
export type TranslationListsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * Filter, which TranslationLists to fetch.
   */
  where: Prisma.TranslationListsWhereUniqueInput
}

/**
 * TranslationLists findFirst
 */
export type TranslationListsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * Filter, which TranslationLists to fetch.
   */
  where?: Prisma.TranslationListsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationLists to fetch.
   */
  orderBy?: Prisma.TranslationListsOrderByWithRelationInput | Prisma.TranslationListsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TranslationLists.
   */
  cursor?: Prisma.TranslationListsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationLists.
   */
  distinct?: Prisma.TranslationListsScalarFieldEnum | Prisma.TranslationListsScalarFieldEnum[]
}

/**
 * TranslationLists findFirstOrThrow
 */
export type TranslationListsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * Filter, which TranslationLists to fetch.
   */
  where?: Prisma.TranslationListsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationLists to fetch.
   */
  orderBy?: Prisma.TranslationListsOrderByWithRelationInput | Prisma.TranslationListsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TranslationLists.
   */
  cursor?: Prisma.TranslationListsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationLists.
   */
  distinct?: Prisma.TranslationListsScalarFieldEnum | Prisma.TranslationListsScalarFieldEnum[]
}

/**
 * TranslationLists findMany
 */
export type TranslationListsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * Filter, which TranslationLists to fetch.
   */
  where?: Prisma.TranslationListsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TranslationLists to fetch.
   */
  orderBy?: Prisma.TranslationListsOrderByWithRelationInput | Prisma.TranslationListsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TranslationLists.
   */
  cursor?: Prisma.TranslationListsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TranslationLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TranslationLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TranslationLists.
   */
  distinct?: Prisma.TranslationListsScalarFieldEnum | Prisma.TranslationListsScalarFieldEnum[]
}

/**
 * TranslationLists create
 */
export type TranslationListsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * The data needed to create a TranslationLists.
   */
  data: Prisma.XOR<Prisma.TranslationListsCreateInput, Prisma.TranslationListsUncheckedCreateInput>
}

/**
 * TranslationLists createMany
 */
export type TranslationListsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TranslationLists.
   */
  data: Prisma.TranslationListsCreateManyInput | Prisma.TranslationListsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TranslationLists createManyAndReturn
 */
export type TranslationListsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * The data used to create many TranslationLists.
   */
  data: Prisma.TranslationListsCreateManyInput | Prisma.TranslationListsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TranslationLists update
 */
export type TranslationListsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * The data needed to update a TranslationLists.
   */
  data: Prisma.XOR<Prisma.TranslationListsUpdateInput, Prisma.TranslationListsUncheckedUpdateInput>
  /**
   * Choose, which TranslationLists to update.
   */
  where: Prisma.TranslationListsWhereUniqueInput
}

/**
 * TranslationLists updateMany
 */
export type TranslationListsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TranslationLists.
   */
  data: Prisma.XOR<Prisma.TranslationListsUpdateManyMutationInput, Prisma.TranslationListsUncheckedUpdateManyInput>
  /**
   * Filter which TranslationLists to update
   */
  where?: Prisma.TranslationListsWhereInput
  /**
   * Limit how many TranslationLists to update.
   */
  limit?: number
}

/**
 * TranslationLists updateManyAndReturn
 */
export type TranslationListsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * The data used to update TranslationLists.
   */
  data: Prisma.XOR<Prisma.TranslationListsUpdateManyMutationInput, Prisma.TranslationListsUncheckedUpdateManyInput>
  /**
   * Filter which TranslationLists to update
   */
  where?: Prisma.TranslationListsWhereInput
  /**
   * Limit how many TranslationLists to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TranslationLists upsert
 */
export type TranslationListsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * The filter to search for the TranslationLists to update in case it exists.
   */
  where: Prisma.TranslationListsWhereUniqueInput
  /**
   * In case the TranslationLists found by the `where` argument doesn't exist, create a new TranslationLists with this data.
   */
  create: Prisma.XOR<Prisma.TranslationListsCreateInput, Prisma.TranslationListsUncheckedCreateInput>
  /**
   * In case the TranslationLists was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TranslationListsUpdateInput, Prisma.TranslationListsUncheckedUpdateInput>
}

/**
 * TranslationLists delete
 */
export type TranslationListsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
  /**
   * Filter which TranslationLists to delete.
   */
  where: Prisma.TranslationListsWhereUniqueInput
}

/**
 * TranslationLists deleteMany
 */
export type TranslationListsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TranslationLists to delete
   */
  where?: Prisma.TranslationListsWhereInput
  /**
   * Limit how many TranslationLists to delete.
   */
  limit?: number
}

/**
 * TranslationLists without action
 */
export type TranslationListsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TranslationLists
   */
  select?: Prisma.TranslationListsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TranslationLists
   */
  omit?: Prisma.TranslationListsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TranslationListsInclude<ExtArgs> | null
}
